### ISSUE TITLE
flux_sync: SecretRef should not be the same as resource name

### ISSUE THREAD

**Issue by Nordes** [fluxcd/terraform-provider-flux#104]
In certain scenario, you would not expect the SecretRef (ssh key) to be the same as the name of the git repository. I don't know if this was chosen by design, but if that's the case it would be better to make it clear in the doc that it will set the same name for the following items:

- GitRepository Resource
    - name
    - secretRef
- Kustomization Resource
    - name

**Comment by hiddeco** [comment]
I [recently made a change](https://github.com/fluxcd/flux2/commit/8a5bba80bf3888b21624a1081c153c9042fe87aa) to the `controllergen` code this module depends on so that it is configurable, so this issue should go away soon-ish.

**Comment by moolen** [comment]
Thanks @hiddeco for making this configurable! However it breaks the current behaviour of the terraform provider and we must take action. 
Previously, the `name` (from the tf-variable) was used as the `GitRepository.name` aswell as the `SecretRef.name`.

With that change the default is now `flux-system` and is **not** configurable anymore from this provider.

I propose to add a variable `secret` which defaults to the tf-variable `name` so we are backwards-compatible again and add it to the options configuration here:

https://github.com/fluxcd/terraform-provider-flux/blob/main/pkg/provider/data_sync.go#L111-L117

WDYT?
I need to check with my client if/how i am allowed to contribute.

**Comment by hiddeco** [comment]
@moolen sorry about that, I was under the impression that the Terraform provider used the `MakeDefaults` option, and [changed accordingly](https://github.com/fluxcd/flux2/blob/8a5bba80bf3888b21624a1081c153c9042fe87aa/pkg/manifestgen/sync/options.go#L42), but forgot to take into account that this would not solve overwrites as you describe them in a backwards compatible manner.

Your suggestion sounds OK to me.
