### ISSUE TITLE
A provider named "flux" could not be found in the Terraform Registry.

### ISSUE THREAD

**Issue by TechGirl-3** [fluxcd/terraform-provider-flux#106]
Hi,

I am using following data-source and but I am not able to install flux provider from the registry. Can you let me know what I am doing wrong here:

data "flux_install" "main" {
  target_path    = "clusters/My-EKS"
  network_policy = false
  version        = "latest"
}

Thanks in Advance.

**Comment by hiddeco** [comment]
![Install instructions](https://user-images.githubusercontent.com/10063039/110107126-cf412f00-7daa-11eb-96e5-a472953e829f.png)

from https://registry.terraform.io/providers/fluxcd/flux/latest
