### ISSUE TITLE
Customize controllers annotations

### ISSUE THREAD

**Issue by glerchundi** [fluxcd/terraform-provider-flux#120]
We want to install flux provider just after we create a GKE cluster. Most of our workloads don't need any kind of access to Google resources but there are specific use cases where this access is needed. For example, when we want to use SOPS and the secrets are encrypted by using a KMS crypto key.

With the latest flux2 manifests adding access to specific controllers is fairly easy by patching the files before making them into the cluster. As those manifest include specific service accounts per controller those can be bound to specific Google Service accounts using Workload Identity.

But the story of applying files "manually" in Terraform is quite broken due to its non-sequential applying nature. Making it non deterministic.

The proposal here would be to surface some parameters that allow us to configure the annotations of the resources being installed. So that we can customize kubernetes service accounts binding them to already existing service accounts to use the Workload Identity feature.

WDTY?

**Comment by phillebaba** [comment]
So I am working on a guide for how to patch the committed kustomize file which would allow you to patch any of the installed resources, do you think that would work for you?

**Comment by cldfzn** [comment]
Is this a terraform kustomization? The current solution (https://github.com/fluxcd/terraform-provider-flux/issues/29) of applying the kustomization in the managed git repository instead of in the terraform configuration creates noise:

1. terraform plan sees extra annotation and says resource needs to be updated
2. terraform apply updates resource
3. flux adds annotation (and requires some annotation to force controller redeploy)
4. rinse and repeat

**Comment by moolen** [comment]
So i think what may be possible is to store the generated flux manifests in a temp file ([example](https://github.com/hashicorp/terraform/issues/21308#issuecomment-721478826)) and use the kbst/kustomize provider with an `kustomization_overlay` ([docs](https://registry.terraform.io/providers/kbst/kustomization/latest/docs/data-sources/overlay#example-usage)) that references that tmp file. From there on you can add patches, commonAnnotations, commonLabels etc.

I'm gonna test this out..

**Comment by glerchundi** [comment]
@phillebaba thanks for the response! I think your proposal could work. Although take into account the explanation below.

@moolen this is what we're doing, take the published manifests, use kustomize patches and commit generated files so that we can apply them into an already created GKE cluster.

But, this has a problem. The snippet below hangs when it tries to apply everything for the first time:

```hcl
resource "kubectl_manifest" "flux_install" {
  provider = kubectl.gke

  count     = length(data.kubectl_file_documents.install_manifests.documents)
  yaml_body = element(data.kubectl_file_documents.install_manifests.documents, count.index)
}

resource "kubectl_manifest" "flux_sync" {
  provider = kubectl.gke

  count     = length(data.kubectl_file_documents.sync_manifests.documents)
  yaml_body = element(data.kubectl_file_documents.sync_manifests.documents, count.index)

  depends_on = [kubectl_manifest.flux_install]
}
```

I'm not quite sure but I guess the problem is in the way Terraform applies resources with count properties. Those are applied in parallel and without following the sequential order these specs require. Imagine that a flux2 manifest is created before even the CRD associated to it was, because Terraform doesn't follow a manifests ordering. Perhaps just splitting CRDs from controllers could make it? I don't know.

What I know is that the first time you create flux, Terraform hangs and you must repeat 2 to 3 times before getting a green light.

I was expecting this problem doesn't happen with this provider and thus I can migrate all of our custom flux applies. In order to do so I needed these controllers customization to allow those use GCP resources (we're using GKE Workload Identity).

Hope it helps

**Comment by glerchundi** [comment]
I confirm that this is what's happening:

```
│ Error: flux-system/helm-controller failed to run apply: error when creating "/tmp/671802041kubectl_manifest.yaml": namespaces "flux-system" not found
...
│ Error: flux-system/image-automation-controller failed to run apply: error when creating "/tmp/029014166kubectl_manifest.yaml": namespaces "flux-system" not found
...
│ Error: flux-system/image-reflector-controller failed to run apply: error when creating "/tmp/963880592kubectl_manifest.yaml": namespaces "flux-system" not found
...
│ Error: flux-system/image-automation-controller failed to run apply: error when creating "/tmp/006159938kubectl_manifest.yaml": namespaces "flux-system" not found
...
│ Error: flux-system/source-controller failed to run apply: error when creating "/tmp/605440236kubectl_manifest.yaml": namespaces "flux-system" not found
...
│ Error: flux-system/helm-controller failed to run apply: error when creating "/tmp/517046959kubectl_manifest.yaml": namespaces "flux-system" not found
```

If I re-run de apply everything works fine.

**Comment by phillebaba** [comment]
So that is one of the limitations right now with the current provider. If you look at the examples you can see that the namespace is created with the Kubernetes Terraform provider.

**Comment by ChrisJBurns** [comment]
@phillebaba  Has been a few months since the last comment, but do you know a way around the above? Am finding that I cannot bring up my cluster with flux in one go due to same errors as above, having to re-run the apply - which from an infrastructure pipeline's perspective won't work.
