### ISSUE TITLE
components_extra applies resources partially

### ISSUE THREAD

**Issue by formatlos** [fluxcd/terraform-provider-flux#126]
I'm wondering if anyone is using the `components_extra` option and also having the same issues.

When I do the following
```
data "flux_install" "main" {
  target_path    = "clusters/my-cluster"
   components_extra = ["image-reflector-controller", "image-automation-controller"]
}
```

Only the service accounts like `image-reflector-controller` and `image-automation-controller` are getting applied, but none of the other resources. 

Might that be related with the remote targets in the flux manifests?

**Comment by dabdada** [comment]
@formatlos and I did some debugging and did see that the flux cli does concat the components and the extraComponents before generating the manifests ([install.go](https://github.com/fluxcd/flux2/blob/dea4a676399a3c63774588b5952e02f0f37d89e0/cmd/flux/install.go#L119-L120)), becuase the template does only iterate over the opts.Components (see [templates.go](https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/templates.go))

We are working on a pull request to concat those provider params before `install.Generate(opts, "")` is called.
