### ISSUE TITLE
Installing on AKS fails to pull image from GHCR

### ISSUE THREAD

**Issue by sudivate** [fluxcd/terraform-provider-flux#131]
I'm trying to install Flux V2 using the terraform provider on a AKS cluster.  However, it fails to pull image from the GitHub container registry

**AKS Version :** 1.19.7 
**Error :** Failed to pull image "ghcr.io/fluxcd/helm-controller:v0.9.0": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/fluxcd/helm-controller:v0.9.0": failed to resolve reference "ghcr.io/fluxcd/helm-controller:v0.9.0": failed to do request: Head https://ghcr.io/v2/fluxcd/helm-controller/manifests/v0.9.0: EOF

Note :  Kubernetes v1.19 or greater default to containerd for its container runtime.

**Comment by phillebaba** [comment]
This sounds like a networking issue as I am running multiple 1.19.7 AKS clusters with Fluxv2 on them. Have you deployed other applications in the cluster which pull images from the public internet? One suggestion is that you deploy [podinfo](https://github.com/stefanprodan/podinfo) manually to see if that works as it will also pull its image from ghcr.

**Comment by sudivate** [comment]
@phillebaba you are right there was firewall rule blocking GHCR. This is good to close.

**Comment by phillebaba** [comment]
Great! Happy to hear that the problem is solved :smile:
