### ISSUE TITLE
Kustomization validation can't be specified in tf 

### ISSUE THREAD

**Issue by samiyaakhtar** [fluxcd/terraform-provider-flux#141]
There's currently no way to specify validation (server or client) when creating the git source and kustomization. 

```
data "flux_sync" "main" {
  name                   = var.flux_resource_name
  count                   = var.flux_applied
  target_path        = var.target_path
  url                = var.url
  branch             = var.branch_name
  namespace          = var.flux_namespace
  interval           = var.sync_interval
  git_implementation = "libgit2"
  secret             = var.flux_secret_name
}
```

Let me know if I'm missing something, I looked in the code and don't think that is exposed.

**Comment by phillebaba** [comment]
We are currently limited to parameters exposed by the options in Fluxv2. If we want to expose the parameter in this provider it first needs to be added here.
https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/sync/options.go

**Comment by phillebaba** [comment]
I have added a new guide in #178 which should cover this issue.
