### ISSUE TITLE
Provide docker image list for flux components

### ISSUE THREAD

**Issue by alialperak** [fluxcd/terraform-provider-flux#148]
It will be great if you can provide list of docker images (especially tags) used in the version set, this would help us mirroring images to our repositories.

**Comment by alialperak** [comment]
This is simple bash solution for now:
```
FLUX_VERSION=v0.13.3
curl -sL https://github.com/fluxcd/flux2/releases/download/$FLUX_VERSION/install.yaml | grep "image: fluxcd/" | awk '{print $2}'
```

**Comment by phillebaba** [comment]
This might be more relevant as an issue under the fluxv2 repo. The versions used by the provider are decided by the version that you set in the data source.  If you explicitly set the version I would think it would solve your problem :smile:
