### ISSUE TITLE
Really long output for Terraform and GitHub Actions

### ISSUE THREAD

**Issue by megawebmaster** [fluxcd/terraform-provider-flux#155]
Hi!

I have a problem with my setup that I don't really know how to solve myself. My setup:
* GKE Private Cluster
* Terraform infrastructure repository
* GitHub Actions applying changes through `dflook/terraform-apply@v1` action

The issue is that output of `terraform plan` has 8039 lines and causes GitHub to fail to add a comment (to show the plan and make sure it matches when applying). Those lines come mostly from `yaml_body_parsed` in `kubectl_manifest`s.

Do you have any idea how to trim this output? Maybe I should file this issue to `kubectl` provider?

**Comment by phillebaba** [comment]
Sorry I have the same problem sometimes but this issue is more related to the kubectl provider rather than the flux provider.

**Comment by megawebmaster** [comment]
I see. Thanks for the input @phillebaba :+1:
