### ISSUE TITLE
Add tag support in flux_sync

### ISSUE THREAD

**Issue by jkotiuk** [fluxcd/terraform-provider-flux#161]
Hey,

Currently flux_sync accept only branch name and it is not possible to use a tag.

When using branch flux will fetch "refs/heads/<branch>"
When using tag flux has to fetch "refs/tags/<tag>"

As you can see those are not interchangeable.

Flux cli already has support for tag and tag-semver as described here: https://fluxcd.io/docs/cmd/flux_create_source_git/

Currently new inactive branch must be created to pin deployment to commit_id, using tags would resolve this issue for us.

**Comment by philnichol** [comment]
Hi, I'd be interested in giving this a go if that's alright? Will depending on the above PR though
