### ISSUE TITLE
Manage Multiple Namespaces

### ISSUE THREAD

**Issue by rajivchirania** [fluxcd/terraform-provider-flux#173]
Hi,
So in flux v1 we had this option which we can use by providing a list of string for the managed namespaces.
In flux v2 while deploying it through terraform i don't see any option where i can define more than 1 namespace which flux v2 should be able manage.
So now the problem is the namespace where i have this gitrepository and kustomization source kind the helm reconciliation works however for other namespace its says HelmChart is not ready

**Comment by rajivchirania** [comment]
@stefanprodan Do you have any idea how we can manage multiple namespace with flux v2

**Comment by stefanprodan** [comment]
Flux v2 manages all namespaces, if it says `HelmChart is not ready` it's not related to namespaces but to miss configuration. See the FAQ here how to debug it: https://fluxcd.io/docs/faq/#how-to-debug-not-ready-errors

**Comment by yashwanth-l** [comment]
@stefanprodan does that mean the `kind: GitRepository`(and its relevant ssh keys as `kind: Secret`) and `kind: Kustomization`) should exist only in `flux-system` namespace?

**Comment by stefanprodan** [comment]
No, you can place them anywhere

**Comment by yashwanth-l** [comment]
GitRepo and Kustomize CRDs are cluster wide since CRDs are always ClusterScope.  Now using this tf module how can we ensure these objects get installed "cluster wide"? @stefanprodan

**Comment by yashwanth-l** [comment]
I mean `Flux v2 manages all namespaces` and without `kind: GitRepository` and `kind: Kustomization` in every namespace the reconciliation isn't working.  Now that this module doesn't have a list ability for a namespace attribute. Its kind of going in a loop to figure this setup around..

**Comment by stefanprodan** [comment]
You got Flux totally wrong, there is no need to place a Kustomization in each namespace, you can structure your manifest and repos in any way you like, a Kustomization can create many namespace and manage all the workloads in there. Also Kustomizations and HelmReleases can use sources (GitRepo, HelmRepo, Buckets) from other namespaces.

**Comment by stefanprodan** [comment]
Maybe this will help: https://fluxcd.io/docs/guides/repository-structure/

**Comment by rajivchirania** [comment]
@stefanprodan Thanks a lot
