### ISSUE TITLE
connection refused kubernetes_namespace.flux-system terraform

### ISSUE THREAD

**Issue by nickazzv** [fluxcd/terraform-provider-flux#180]
tyring to create a flux regarding to your settings, but keep facing that issue, googled a little they say have to add load_configuration_file = false to kubernetes provider, i did but in this case i have new issue whick is " An argument named "load_config_file" is not expected here." need your help asap

**Comment by kingdonb** [comment]
Please check the example and see if your terraform config differs somehow:

https://www.terraform.io/docs/language/settings/backends/kubernetes.html#example-configuration

Please also provide the versions of all tools involved, in case this option was not available in a prior version. Terraform, the terraform-provider-flux, the Kubernetes provider, all versions in use.

We will need at least this much information to help diagnose your issue. It would probably help us out to provide the content of the `.tf` file that failed, as well. Thanks for using Flux!

**Comment by phillebaba** [comment]
Closing this issue as it seems more related to issues with the kubectl provider rather than the flux provider.
