### ISSUE TITLE
Image update automation: The key is read only

### ISSUE THREAD

**Issue by Smana** [fluxcd/terraform-provider-flux#181]
Hi everyone,

Is there a way to write a read/write key? Currently, I'm not able to use image update automation.

Thanks for the support,

**Comment by yebyen** [comment]
Do you have this section in your config, from the GitHub docs:

```
resource "github_repository_deploy_key" "main" {
  title      = "staging-cluster"
  repository = github_repository.main.name
  key        = tls_private_key.main.public_key_openssh
  read_only  = true
}
```

Looks like you can change it there

**Comment by Smana** [comment]
Ideed, thank you @yebyen , that worked :)
