### ISSUE TITLE
connectex: No connection could be made because the target machine actively refused  with kubernetes_namespace.flux_system

### ISSUE THREAD

**Issue by gtncloud** [fluxcd/terraform-provider-flux#185]
Hi,

we are trying to install fluxcd to azure k8s and getting below error, can someone please help 

# Kubernetes
resource "kubernetes_namespace" "flux_system" {
  metadata {
    name = "flux-system"
  }

  lifecycle {
    ignore_changes = [
      metadata[0].labels,
    ]
  }
}

Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused 
it.
│
│   with kubernetes_namespace.flux_system,
│   on fluxcd.tf line 23, in resource "kubernetes_namespace" "flux_system":
│   23: resource "kubernetes_namespace" "flux_system" {

**Comment by phillebaba** [comment]
Great, sounds like it fixed the problem!
