### ISSUE TITLE
flux_sync may produce incompatible documents

### ISSUE THREAD

**Issue by or-shachar** [fluxcd/terraform-provider-flux#201]
`flux_install` has a useful attribute `version` which allows us to lock the installed component version.

`flux_sync` produces kustomization document that are only compatible with the unconfigurable default version.

Just had a very serious issue (luckily on stage) with the new **Flux Provider 0.4.0** where terraform failed to create the new terraform kustomziation document (it was incompitible with Flux 0.17.x, which I use), so it removed it, and then my Kustomization controller removed all of components that were installed using Flux.

Solutions alternatives:
1. Remove the `version` attribute from `flux_install`.
2. Add `version` attribute to `flux_sync`

**Comment by phillebaba** [comment]
Closing this issue now.
