### ISSUE TITLE
Upgrading flux breaks when Kustomization API signature changes 

### ISSUE THREAD

**Issue by neillturner** [fluxcd/terraform-provider-flux#230]
Seems to be problems when a new version of flux or the provisioner is released.
terraform will delete the existing flux and try and install the new flux version which often fails. 
Trying to find a reliable way to upgrade flux

**Comment by stefanprodan** [comment]
I'm guessing you haven't seen https://github.com/fluxcd/terraform-provider-flux/blob/main/CHANGELOG.md#040

**Comment by neillturner** [comment]
thanks for your response. I think we are going to try using the community helm charts https://github.com/fluxcd-community/helm-charts/tree/main/charts as they seem a little less magically to my simple mind compared to flux bootstrap and the terraform flux provider.

**Comment by neillturner** [comment]
Yes it broke because of https://github.com/fluxcd/terraform-provider-flux/blob/main/CHANGELOG.md#040. 
you say that it will be fixed in a later version of the provider. Is there a "safe" version of the flux provider to upgrade to from version 0.2.0.

**Comment by neillturner** [comment]
It seems to me that the flux provider when the kustomization resource changes its api signature from say beta1 to beta2 causes the customization resource to be destroy and created  (even if you save to terraform ignore changes - ignore changes means just don't do updates).

**Comment by neillturner** [comment]
maybe its possible to write a bit of code that checks the version of the flux provider in the state and if it is 0.3.1 or less then write out a WARNING messages to run

**Comment by neillturner** [comment]
What i do is lock both the flux version and the flux provider version:
