### ISSUE TITLE
Data Source `flux_install` Supports `version` but  `flux_sync` Doesn't

### ISSUE THREAD

**Issue by Efrat19** [fluxcd/terraform-provider-flux#274]
Hi
I would like to manage my versions independently and be able to upgrade flux version in my scheduled maintenance time. I am able to [pin the version](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/data-sources/install#version) on the `flux_install` data source, unfortunately such property is not available on `flux_sync` and terraform will always plan to deploy the latest version flux version which obviously causes a version mismatch error unless I use the latest version on the `flux _install` too:
```
Error: flux-system/flux-system failed to create kubernetes rest client for update of resource: resource [source.toolkit.fluxcd.io/v1beta2/GitRepository] isn't valid for cluster, check the APIVersion and Kind fields are valid
```
I was hoping you will provide a way to pin `flux_sync`  data source versions too
Thank you!

**Comment by kingdonb** [comment]
I think the terraform provider that generates manifests for a `flux_sync` is only going to stock the latest API version, I'm not sure at what stage this failure happens, but hopefully it is early enough (during `tf plan`) to avoid deployment failures.

https://github.com/fluxcd/terraform-provider-flux/blob/dc16077de28d28661398f44d0aced63d7e0b96ae/examples/github/main.tf#L17-L20

These manifests are generated based on supplied configuration, where the install manifests are pulled from a release archive, so I think it's not trivial to support multiple API versions at once. I don't think it's supported to pin the `--version` at install time for now. You can pin the version of the provider itself as shown here in the example linked above, though.

In general, the position of the Flux project before GA milestone is reached has been that, new releases will only support installing the latest API versions, and older versions that were already installed on the cluster are able to be automatically upgraded via the Kubernetes API, for backward compatibility (to support upgrading from earlier versions) – but they will not be served or installable on the cluster after the upgrade. This unfortunately also means, one cannot use a newer version of Flux CLI or provider to install an older version of Flux, if this crosses an API release boundary like this week's releases do.

This position may have to be re-evaluated after GA milestone is reached, and the APIs all are promoted to v1, but before then we're unlikely to see CLI or provider binaries that support a matrix of releases crossing API upgrades.

**Comment by Efrat19** [comment]
Solved my issue, thank you @kingdonb
