### ISSUE TITLE
How to install extra components like image-reflector-controller,image-automation-controller using Fluxv2 Terraform module?

### ISSUE THREAD

**Issue by youwalther65** [fluxcd/terraform-provider-flux#279]
I use the following Terraform Fluxv2 provider
provider "registry.terraform.io/fluxcd/flux" {
  version     = "0.12.2"
...

Looking at flux-system namespace there are no deployments for image-reflector-controller and/or image-automation-controller. At the moment I see no option to customize using the TF resourcs flux_install  . Is this a point for development or am I missing an option here?

**Comment by stefanprodan** [comment]
Please see https://github.com/fluxcd/terraform-provider-flux/blob/main/pkg/provider/data_install.go#L80

**Comment by youwalther65** [comment]
Sorry for that and thank you for the fast response. Really forgot to look at doc: https://registry.terraform.io/providers/fluxcd/flux/latest/docs/data-sources/install#components_extra
