### ISSUE TITLE
Support PSP enabled clusters

### ISSUE THREAD

**Issue by mbastawisy** [fluxcd/terraform-provider-flux#281]
Currently, this terraform provider doesn't allow customizing the `flux_install` data source to allow the installation on `podsecuritypolicies` enabled clusters.

### Context

- There are four controllers that come with the default installation, two of them (which are `kustomize-controller` and `helm-controller`) are running with a cluster-admin role and two (`source-controller` and `notification-controller`) are running with a custom role binding that is not allowing any `podsecuritypolicies`.

-  During the installation of this terraform provider, the `flux_install` YAML files fail during the apply step since the source & notification controllers can't create any pods because of the insufficient privileges they have, and hence the deployment fails.

- Tried to override the cluster role `crd-controller-flux-system` using `flux_sync` data source however terraform doesn't reach this step because of the failure from the `flux_install`.

### Proposed Solutions

- Best solution: provide a single data source that would compile both data sources together and apply the final YAML files as expected

- maybe provide a helm chart that is customizable instead of a custom terraform provider

**Comment by stefanprodan** [comment]
> maybe provide a helm chart that is customizable instead of a custom terraform provider

See https://artifacthub.io/packages/helm/fluxcd-community/flux2
