### ISSUE TITLE
permadrift / idempotency with image-reflector component

### ISSUE THREAD

**Issue by wyardley** [fluxcd/terraform-provider-flux#293]
I've mostly no longer had to use `ignore_fields` or seen `yaml_incluster` drift since the comments towards the end of https://github.com/gavinbunney/terraform-provider-kubectl/issues/92. https://github.com/fluxcd/terraform-provider-flux/pull/283 suggests that it may still be necessary in some cases. What I'm seeing is that with `image-reflector-controller` in the extra components, we will get _very_ frequent drift where the provider shows something changing like:

```
  # module.flux2.kubectl_manifest.install["apps/v1/deployment/flux-system/image-reflector-controller"] will be updated in-place
  ~ resource "kubectl_manifest" "install" {
        id                      = "/apis/apps/v1/namespaces/flux-system/deployments/image-reflector-controller"
        name                    = "image-reflector-controller"
      ~ yaml_incluster          = (sensitive value)
```

that's even with adding / applying `ignore_fields` as follows:
```hcl
data "flux_install" "main" {
  target_path = var.target_path
  components_extra = [
    "image-automation-controller",
    "image-reflector-controller",
  ]
}
[...]
resource "kubectl_manifest" "install" {
  for_each   = { for v in local.install : lower(join("/", compact([v.data.apiVersion, v.data.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
  depends_on = [kubernetes_namespace.flux_system]
  yaml_body  = each.value
  ignore_fields = ["metadata.annotations", "status"]
}
```

I don't see any other unusual fields in `metadata` from a quick look that other components don't have... any idea what it might be? Before we added this component, most of our permadrift problems had gone away (even without `ignore_fields` being set).

And, is there any (easy) way to debug what it's wanting to change it based on?

**Comment by markgloz** [comment]
I am getting the same issue.

**Comment by wyardley** [comment]
I've got it working Ok now, using latest flux, latest version of this provider
```hcl
resource "kubectl_manifest" "install" {
  for_each   = { for v in local.install : lower(join("/", compact([v.data.apiVersion, v.da
ta.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
  yaml_body  = each.value

  // wasn't necessary any more, but still seems needed for image-reflector-controller
  ignore_fields = ["metadata.annotations", "spec"]
}
```

This ended up being the meat of what seemed to resolve it for us.
