### ISSUE TITLE
Add custom label on pods deployed in flux-system namespace

### ISSUE THREAD

**Issue by ericmenard** [fluxcd/terraform-provider-flux#310]
Hi, 

I would like to add my own labels on the pods deployed by terraform during flux installation.
These are the pods running on my cluster after installation
helm-controller-544df4db67-l7hh8          1/1     Running   0          2d6h
kustomize-controller-5f964db78c-6xfbh     1/1     Running   0          2d6h
notification-controller-b55cbcf9c-vltfz   1/1     Running   0          2d6h
source-controller-84897ffd55-qqkv2        1/1     Running   0          2d6h

Something such labels in the terraform provider could do the job with {} as default value.

Thanks

**Comment by phillebaba** [comment]
I wrote a guide for this a while back.

http://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/customize-flux
