### ISSUE TITLE
Use gitlab_deploy_token instead of gitlab_deploy_key for bootstrapping flux example

### ISSUE THREAD

**Issue by oxr463** [fluxcd/terraform-provider-flux#316]
Reference(s):
- https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/deploy_token

**Comment by swade1987** [comment]
@oxr463, can a `deploy_token` be used to write to the GitLab project? see https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/deploy_token#scopes

**Comment by oxr463** [comment]
Hmm you might be right, https://gitlab.com/gitlab-org/gitlab/-/issues/23067
