### ISSUE TITLE
TF controller pod is throwing an error  crashloopbackoff after the installation 

### ISSUE THREAD

**Issue by eravindar12** [fluxcd/terraform-provider-flux#321]
I am getting the following error when I install the terraform controller on flux v2.
How to fix this issue?

tf-controller-7ff4f9d84b-s59wf                0/1     CrashLoopBackOff   5          5m20

k logs -f tf-controller-7ff4f9d84b-s59wf -n flux-system --previous
+ kubectl logs -f tf-controller-7ff4f9d84b-s59wf -n flux-system --previous
unknown flag: --runner-creation-timeout
Usage of tf-controller:
      --ca-cert-validity-duration duration        The duration that the ca certificate certificates should be valid for. Default is 1 week. (default 168h0m0s)
      --cert-rotation-check-frequency duration    The interval that the mTLS certificate rotator should check the certificate validity. (default 30m0s)
      --cert-validity-duration duration           The duration that the mTLS certificate that the runner pod should be valid for. (default 6h0m0s)
      --concurrent int                            The number of concurrent terraform reconciles. (default 4)
      --enable-leader-election                    Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
      --events-addr string                        The address of the events receiver.
      --health-addr string                        The address the health endpoint binds to. (default ":9440")
      --http-retry int                            The maximum number of retries when failing to fetch artifacts over HTTP. (default 9)
      --kube-api-burst int                        The maximum burst queries-per-second of requests sent to the Kubernetes API. (default 50)
      --kube-api-qps float32                      The maximum queries-per-second of requests sent to the Kubernetes API. (default 20)
      --leader-election-lease-duration duration   Interval at which non-leader candidates will wait to force acquire leadership (duration string). (default 35s)
      --leader-election-release-on-cancel         Defines if the leader should step down voluntarily on controller manager shutdown. (default true)
      --leader-election-renew-deadline duration   Duration that the leading controller manager will retry refreshing leadership before giving up (duration string). (default 30s)
      --leader-election-retry-period duration     Duration the LeaderElector clients should wait between tries of actions (duration string). (default 5s)
      --log-encoding string                       Log encoding format. Can be 'json' or 'console'. (default "json")
      --log-level string                          Log verbosity level. Can be one of 'trace', 'debug', 'info', 'error'. (default "info")
      --metrics-addr string                       The address the metric endpoint binds to. (default ":8080")
      --requeue-dependency duration               The interval at which failing dependencies are reevaluated. (default 30s)
      --runner-grpc-port int                      The port which will be exposed on the runner pod for gRPC connections. (default 30000)
      --watch-all-namespaces                      Watch for custom resources in all namespaces, if set to false it will only watch the runtime namespace. (default true)
**unknown flag: --runner-creation-timeout**

**Comment by stefanprodan** [comment]
This repository is for the Flux Terraform Provider which is not the same with tf-controller. Please open an issue on https://github.com/weaveworks/tf-controller
