### ISSUE TITLE
generated kustomize.yaml is not valid yaml

### ISSUE THREAD

**Issue by jodok** [fluxcd/terraform-provider-flux#352]
i'm running yamllint on all manifests as github action.

the generated kustomize.yaml starts with a newline. it should either start with the first key, or even better with `---`

My pull request https://github.com/fluxcd/terraform-provider-flux/pull/351 is fixing it.

**Comment by swade1987** [comment]
Closing, see https://github.com/fluxcd/terraform-provider-flux/pull/351#issuecomment-2044692422 for justification.
