### ISSUE TITLE
flux bootstrap with Bitbucket Cloud

### ISSUE THREAD

**Issue by shaikhtousif1** [fluxcd/terraform-provider-flux#353]
Hi I want to how to bootstrap flux with Bitbucket cloud as repo?

I am trying to bootstrap flux with my repo inside bitbucket cloud (using CLI as well as Terraform)

Can you please help me with some example?

**Comment by preston-willis** [comment]
I'm trying to do the same. Is there any way to do this or plans to integrate this feature in the future?
Thanks!

**Comment by shaikhtousif1** [comment]
Yes... I figured it out... You need to use flux git command 

Here is the sample command

flux bootstrap git \
--url=ssh://bitbucket.org/mycode/prod-flux-cd-setup.git \
--path=clusters/prod-my-cloud \
--branch=main \
--token-auth=true \
--ssh-key-algorithm=rsa \
--private-key-file=/Users/myuser/.ssh/id_rsa \
--insecure-skip-tls-verify=true

**Comment by preston-willis** [comment]
How would this be done in a terraform file?

**Comment by shaikhtousif1** [comment]
This thing is not supported in terraform... even  when i was using the gitlab i deployed flux with terraform...but since we migrated the code to bitbucket i am bootstraping it with cli command

**Comment by preston-willis** [comment]
Good to know! What if I need to dynamically create clusters with terraform? Should I just move my flux repo to GitHub? Thanks for the help!

**Comment by shaikhtousif1** [comment]
yes..it will work...you can follow the flux documentation for the same.

**Comment by kingdonb** [comment]
There is a flux bootstrap git provider in the terraform provider now, not sure when was the last time you looked at the terraform provider but it uses generic git and should work with any git host. It has had major changes since the flux install provider that worked together with the kubernetes provider.

https://github.com/fluxcd/terraform-provider-flux

The challenging part might be creating the repos with terraform and adding the ssh key or token secret, since all that must happen outside of Flux.

**Comment by shaikhtousif1** [comment]
Thanks @kingdonb for the reply...i used the flux terraform 6 month back.. I will check now

**Comment by shaikhtousif1** [comment]
@preston-willis 

See the code i used for bitbucket cloud with generic git resource

provider "flux" {
  kubernetes = {
  host                   = var.host
  password               = var.password
  cluster_ca_certificate = base64decode(var.cluster_ca_certificate)
  client_certificate     = base64decode(var.client_certificate)
  client_key             = base64decode(var.client_key)
}
  
  git = {
    url = "ssh://git@bitbucket.org/brassteal/non-prod-flux-cd-setup.git"
    ssh = {

        branch = "master"
        private_key= file("/Users/mylocal/.ssh/id_rsa")  # for now change this to your local private key location

    }
  }
}

 provider kubernetes  {
  host                   = var.host
  password               = var.password
  username               = var.username
  cluster_ca_certificate = base64decode(var.cluster_ca_certificate)
  client_certificate     = base64decode(var.client_certificate)
  client_key             = base64decode(var.client_key)
}

resource "flux_bootstrap_git" "this" {
  path = "clusters/my-aks-cluster"
   components_extra = [
    "image-reflector-controller",
    "image-automation-controller",
  ] 
}
