### ISSUE TITLE
Add tag support in new `flux_bootstrap_git` terraform resource 

### ISSUE THREAD

**Issue by jamiezieziula** [fluxcd/terraform-provider-flux#366]
Similar to [this](https://github.com/fluxcd/terraform-provider-flux/issues/161) issue - introduce the ability to specify a tag to sync a git repo from.

**Comment by stefanprodan** [comment]
Bootstrap means pushing the Flux manifests to a branch, it can’t be tag, that’s a pointer to a specific commit.

**Comment by phillebaba** [comment]
Closing this as it is not something that we can implement.

**Comment by jamiezieziula** [comment]
Hey @phillebaba and @stefanprodan - thanks, I think i misunderstood the implementation at first. I understand that for the flux manifests - pushing to a branch makes sense.

But how can i specify a tag for a gitrepo to watch like was being done previously by [this](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/data-sources/sync#tag) code?
