### ISSUE TITLE
The input validation to strict for url?

### ISSUE THREAD

**Issue by nlarzon** [fluxcd/terraform-provider-flux#38]
Error: expected "url" to be a valid url, got ssh://git@codeberg.org:username/fluxv2.git: parse "ssh://git@codeberg.org: username/fluxv2.git": invalid port ": username" after host

I got this error while trying to make an example for generic git repo.

**Comment by hiddeco** [comment]
`ssh://git@codeberg.org:username/fluxv2.git` is a ["shorter" scp-like syntax for the SSH protocol](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_ssh_protocol) that `git` does support, but not a [RFC 3986 compatible scheme](https://tools.ietf.org/html/rfc3986#section-3) that we support.

Changing your URL to `ssh://git@codeberg.org/username/fluxv2.git` should make it work.
