### ISSUE TITLE
Error after terraform apply using flux_bootstrap_git resource: "Expected configured provider clients"

### ISSUE THREAD

**Issue by tyhawkins** [fluxcd/terraform-provider-flux#387]
I am attempting to bootstrap a cluster with Flux using the `flux_bootstrap_git` resource, but I receive the error "Expected configured provider clients."

Here is the output of my `terraform apply`:

```console
$ terraform apply       

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # flux_bootstrap_git.this will be created
  + resource "flux_bootstrap_git" "this" {
      + author_name          = "Flux"
      + branch               = "master"
      + cluster_domain       = "cluster.local"
      + components           = [
          + "helm-controller",
          + "kustomize-controller",
          + "notification-controller",
          + "source-controller",
        ]
      + components_extra     = [
          + "image-automation-controller",
          + "image-reflector-controller",
        ]
      + id                   = (known after apply)
      + interval             = "1m0s"
      + log_level            = "info"
      + namespace            = "flux-system"
      + network_policy       = true
      + path                 = "clusters/new-cluster"
      + registry             = "ghcr.io/fluxcd"
      + repository_files     = (known after apply)
      + secret_name          = "flux-system"
      + ssh                  = {
          + private_key = (sensitive value)
          + username    = "git"
        }
      + url                  = "ssh://git@gitlab.example.com/devsecops/gitops/fleet-infra.git"
      + version              = "v0.40.1"
      + watch_all_namespaces = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

flux_bootstrap_git.this: Creating...
╷
│ Error: Unconfigured Clients
│ 
│   with flux_bootstrap_git.this,
│   on main.tf line 49, in resource "flux_bootstrap_git" "this":
│  147: resource "flux_bootstrap_git" "this" {
│ 
│ Expected configured provider clients.
╵
Releasing state lock. This may take a few moments...
```

Here is my code

```terraform
terraform {
  required_providers {
    flux = {
      source = "fluxcd/flux"
      version = "0.24.2"
    }
    # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 2.18"
    }
    helm = {
      source = "hashicorp/helm"
      version = "~> 2.9"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "~> 1.14"
    }
    # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  }
}

# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
provider "kubernetes" {
  config_path    = pathexpand("~/.kube/config")
  config_context = "new-cluster"
}

provider "helm" {
  kubernetes {
    config_path    = pathexpand("~/.kube/config")
    config_context = "new-cluster"
  }
}

provider "kubectl" {
  config_path    = pathexpand("~/.kube/config")
  config_context = "new-cluster"
  load_config_file = true
}
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

provider "flux" {
  config_path = pathexpand("~/.kube/config")
  config_context = "new-cluster"
}

resource "flux_bootstrap_git" "this" {
  url  = "ssh://git@gitlab.example.com/devsecops/gitops/fleet-infra.git"
  branch = "master"
  path = "clusters/new-cluster"
  ssh = {
    username    = "git"
    private_key = file(pathexpand("~/.ssh/terraform_flux_bootstrap"))
  }
  version = "v0.40.1"
  watch_all_namespaces = false
  components_extra = [
    "image-reflector-controller",
    "image-automation-controller"
  ]
}
```

I have tried with and without the sections indicated by the `# vvvvv` comments to no effect.

**Comment by phillebaba** [comment]
Regarding the poor error messages, that is something I have fixed in a PR that is yet to be merged. So hopefully that should be out soon.

Before digging any deeper, have you checked that the kube config file and context exists? It might be a stupid question but it's an easy mistake to make.

**Comment by tyhawkins** [comment]
That was the problem. The documentation only says this about contexts:
> The current context set in the kubeconfig file will be used by default.

But looking through the code, `config_context` seemed to be implemented so I was testing with a nonexistent context expecting an error to confirm that if you specify a context, it does **not** use the current context. The error message didn't mention contexts so it led me down this rabbit hole.

I've opened a pull request for the attribute descriptions so others can have more faith that they work as intended. Your PR for the other issue should address the situation that caused this issue.

**Comment by swade1987** [comment]
@tyhawkins The version of flux used by `flux_bootstrap_git` is tightly coupled to the version of the provider version.

Therefore I would only recommend setting the version in the `flux_bootstrap_git` resource if we introduce a bug.

I would recommend using the following provider versions:

```
terraform {
  required_version = ">= 1.7.0"

  required_providers {
    flux = {
      source  = "fluxcd/flux"
      version = ">= 1.2"
    }
}
```

Then the following provider configuration for the flux provider:

```
provider "flux" {
  kubernetes = {
    config_path = "~/.kube/config"
  }
  git = {
    url = "ssh://git@gitlab.example.com/devsecops/gitops/fleet-infra.git"
    ssh = {
      username    = "git"
      private_key = REDACTED
    }
  }
}
```

Finally, the following resource specification 

```
resource "flux_bootstrap_git" "this" {
  path = "clusters/new-cluster"
  components_extra = [
    "image-reflector-controller",
    "image-automation-controller"
  ]
}
```

**Comment by swade1987** [comment]
Hello @tyhawkins  👋 

I hope all is well with you. I'm just contacting you as part of our initiative to ensure the quality and responsiveness of our project's issue tracking. Thank you for your previous contributions by reporting issues you've encountered; your engagement is invaluable to the health and progress of our project.

I've reviewed the issue you reported and noted that it involves using supported resources, which is great. However, I also noticed that there has been little activity on this issue lately. We understand that circumstances change and priorities shift, which may affect the urgency or relevance of an issue.

We're implementing a policy regarding inactive issues to keep our project's issue tracker effective and up-to-date. If there's no further activity on this issue within the next 3 weeks, we will mark it inactive and close it. This approach helps us maintain focus on current and actively pursued concerns, ensuring resources are well allocated.

That said, we are still very much interested in resolving the issue you've encountered. If the problem persists or if you have any new information that could help us address it, please don't hesitate to update the issue or comment. Your input could be crucial in finding a resolution. Alternatively, if the issue no longer affects you or has been resolved, let us know so we can close it with the right resolution.

We're here to support and work with you to overcome any challenges you face using our project. Your continued feedback and participation are essential to our community's success.

Thank you once again for your contribution. I look forward to your update and am here to assist with any further questions or issues you might have.

Best regards,

Steve

**Comment by tyhawkins** [comment]
This can be closed, I'll close it.
