### ISSUE TITLE
BUG: toleration_keys lowercase RFC1123

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/terraform-provider-flux#389]
Currently a taint of `CriticalAddonsOnly` can't be tolerated due to this constraint:

```
╷
│ Error: Invalid Attribute Value Match
│
│   with flux_bootstrap_git.this,
│   on flux.tf line 27, in resource "flux_bootstrap_git" "this":
│   27:   toleration_keys        = ["CriticalAddonsOnly"]
│
│ Attribute toleration_keys[Value("CriticalAddonsOnly")] a lowercase RFC 1123 label must consist of lower case alphanumeric characters
│ or '-', and must start and end with an alphanumeric character, got: CriticalAddonsOnly
```

/label bug

**Comment by phillebaba** [comment]
I misread the API documentation. It states the following regarding taint keys.

> The key is any string, up to 253 characters. The key must begin with a letter or number, and may contain letters, numbers, hyphens, dots, and underscores.

I would rather add this validation instead of just removing the RFC1123 validation. Do you want to update your PR?

**Comment by cdenneen** [comment]
@phillebaba I allowed edits on the PR. I honestly wouldn't know where to start.

**Comment by phillebaba** [comment]
I created a new PR to fix this with a proper validator. You can close your PR. The fix should be out in the next release.

**Comment by cdenneen** [comment]
@phillebaba any ETA on release?
