### ISSUE TITLE
Switching branch in `flux_bootstrap_git` shouldn't force a replacment

### ISSUE THREAD

**Issue by sereinity** [fluxcd/terraform-provider-flux#398]
Hello,

While working on flux or other integrations, I frequently switch branch, but doing it with the new `flux_bootstrap_git` forces to reinstall flux, which it troublesome (didn't test it, but I think it will break many thing).

I think it should be able to change the branch in the `gitrepository` object without breaking flux.

I managed to prevent the deletion of flux by:
- Patching the gitrepository
- `terraform state rm flux_bootstrap_git.this`
- `terraform import flux_bootstrap_git.this flux-system`

Also, refreshing the resource should detect branch changes.

Thanks in advance.

**Comment by phillebaba** [comment]
After moving the git configuration to the provider this is not an issue anymore as it does not force a new resource. Please reopen the issue if you are still having issues.
