### ISSUE TITLE
Create GPG key to sign provider binary

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/terraform-provider-flux#4]
Publishing to the provider to the Terraform registry requires a SHA256SUMS file that is signed by a trusted GPG private key.

The private key needs to be added as a secret with the key `GPG_PRIVATE_KEY` in the repository. The public key needs to be added to the organization in the terraform registry.

For more details refer to the Terraform documentation.
https://www.terraform.io/docs/registry/providers/publishing.html#preparing-and-adding-a-signing-key
https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-

**Comment by stefanprodan** [comment]
I've generated a PGP key for fluxcdbot and I've added GH secrets and TF public key

<img width="927" alt="Screenshot 2020-11-02 at 13 03 55" src="https://user-images.githubusercontent.com/3797675/97861143-feb43200-1d0b-11eb-8c39-1594941e1527.png">
<img width="1025" alt="Screenshot 2020-11-02 at 13 03 41" src="https://user-images.githubusercontent.com/3797675/97861149-01af2280-1d0c-11eb-80fc-fa2818ba298b.png">

**Comment by phillebaba** [comment]
We can close this now as the key works and we have published our first release.
