### ISSUE TITLE
version 0.25.0 does not honor components_extra

### ISSUE THREAD

**Issue by balonik** [fluxcd/terraform-provider-flux#407]
Provider version 0.25.0 does not honor `components_extra` parameter for data source `flux_install`.

For existing installation it wants to remove all related resources in plan. I have `components_extra = ["image-reflector-controller", "image-automation-controller"]` set.

Snippets from the plan:
```
# module.flux-v2.kubectl_manifest.install["apps/v1/deployment/flux-system/image-automation-controller"] will be destroyed
...
# module.flux-v2.kubectl_manifest.install["apps/v1/deployment/flux-system/image-reflector-controller"] will be destroyed
...
# module.flux-v2.kubectl_manifest.install["v1/serviceaccount/flux-system/image-reflector-controller"] will be destroyed
...
# module.flux-v2.kubectl_manifest.install["v1/serviceaccount/flux-system/image-automation-controller"] will be destroyed
...
```

workaround is to revert back to 0.24.2 version.

**Comment by balonik** [comment]
Maybe related to https://github.com/fluxcd/terraform-provider-flux/pull/396?

**Comment by phillebaba** [comment]
#396 fixes the import code in the bootstrap resource, so it has no impact on the datasources. Will have a look at what is going on with the data source and components_extra.
