### ISSUE TITLE
`flux_bootstrap_git` unknown error: Unauthorized

### ISSUE THREAD

**Issue by adampayz** [fluxcd/terraform-provider-flux#417]
Hi,

I'm getting the below error when trying to run `terraform apply`.

```bash
flux_bootstrap_git.eco_helm: Modifying... [id=flux-system]
╷
│ Error: Unable to push updated files
│
│   with flux_bootstrap_git.eco_helm,
│   on flux.tf line 118, in resource "flux_bootstrap_git" "eco_helm":
│  118: resource "flux_bootstrap_git" "eco_helm" {
│
│ unknown error: Unauthorized
```

Here's my `fluxcd` provider config and I'm using the latest version of the provider `v0.25.1`:

```
provider "flux" {
  kubernetes = {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
  git = {
    url    = "ssh://git@bitbucket.org/${var.repo}.git"
    branch = var.branch
    
    ssh = {
      username    = "git"
      private_key = tls_private_key.main.private_key_pem
    }
  }
}
```

**Comment by phillebaba** [comment]
Have you checked that the TLS key that you are passing to Flux has write permissions to the repository?

**Comment by adampayz** [comment]
> Have you checked that the TLS key that you are passing to Flux has write permissions to the repository?

Yes, I have this code to deploy the key to the repo
```bash
resource "bitbucket_deploy_key" "eco_helm" {
  workspace  = var.workspace
  repository = var.repo
  key        = tls_private_key.main.public_key_openssh
}
```

**Comment by adampayz** [comment]
Does this provider supports repo stored in bitbucket?

**Comment by nw-code** [comment]
I'm using GitLab and had a similar error:
```
╷                                       
│ Error: Unable to push updated files
│             
│   with flux_bootstrap_git.main,
│   on main.tf line 16, in resource "flux_bootstrap_git" "main":      
│   16: resource "flux_bootstrap_git" "main" {
│ 
│ unknown error: remote:                             
╵                    
```
```
provider "flux" {
  kubernetes = {
    config_context = var.config_context
    config_path    = "~/.kube/config"
  }
  git = {
    url    = "ssh://gitlab.com/${var.gitlab_project}.git"
    branch = "master"
    ssh = {
      private_key = tls_private_key.main.private_key_pem
      username    = "git"
    }
  }
}
```
I was under the (false) impression that the TLS key didn't need write permission. Once I corrected that, it worked.

**Comment by nw-code** [comment]
> > I'm using GitLab and had a similar error:
> > ```
> > ╷                                       
> > │ Error: Unable to push updated files
> > │             
> > │   with flux_bootstrap_git.main,
> > │   on main.tf line 16, in resource "flux_bootstrap_git" "main":      
> > │   16: resource "flux_bootstrap_git" "main" {
> > │ 
> > │ unknown error: remote:                             
> > ╵                    
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > provider "flux" {
> >   kubernetes = {
> >     config_context = var.config_context
> >     config_path    = "~/.kube/config"
> >   }
> >   git = {
> >     url    = "ssh://gitlab.com/${var.gitlab_project}.git"
> >     branch = "master"
> >     ssh = {
> >       private_key = tls_private_key.main.private_key_pem
> >       username    = "git"
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I was under the (false) impression that the TLS key didn't need write permission. Once I corrected that, it worked.
> 
> How did you correct it?

I added write permission (`can_push = true`) to my key:
```
resource "gitlab_deploy_key" "main" {
  can_push = true
  key      = tls_private_key.main.public_key_openssh
  project  = data.gitlab_project.main.id
  title    = var.cluster
}
```

**Comment by phillebaba** [comment]
I have written a guide for GitHub. I will try to get a PR done for GitLab and Bitbuck soon to cover both of these use cases. It's a bit easier to create guides for the new resource as there are not as many specific integrations with each Git provider.

**Comment by adampayz** [comment]
> I have written a guide for GitHub. I will try to get a PR done for GitLab and Bitbuck soon to cover both of these use cases. It's a bit easier to create guides for the new resource as there are not as many specific integrations with each Git provider.

Can you please let me know once you've created a PR for bitbucket. Thanks!

**Comment by adampayz** [comment]
@nw-code `bitbucket_deploy_key` doesn't have that argument `can_push`.

**Comment by joivo** [comment]
Any news on this?

**Comment by swade1987** [comment]
@adampayz did you manage to get this resolved? If so would you be happy to submit a PR for an example using Bitbucket?

**Comment by swade1987** [comment]
Hello @adampayz  👋 

I hope all is well with you. I'm just contacting you as part of our initiative to ensure the quality and responsiveness of our project's issue tracking. Thank you for your previous contributions by reporting issues you've encountered; your engagement is invaluable to the health and progress of our project.

I've reviewed the issue you reported and noted that it involves using supported resources, which is great. However, I also noticed that there has been little activity on this issue lately. We understand that circumstances change and priorities shift, which may affect the urgency or relevance of an issue.

We're implementing a policy regarding inactive issues to keep our project's issue tracker effective and up-to-date. If there's no further activity on this issue within the next 3 weeks, we will mark it inactive and close it. This approach helps us maintain focus on current and actively pursued concerns, ensuring resources are well allocated.

That said, we are still very much interested in resolving the issue you've encountered. If the problem persists or if you have any new information that could help us address it, please don't hesitate to update the issue or comment. Your input could be crucial in finding a resolution. Alternatively, if the issue no longer affects you or has been resolved, let us know so we can close it with the right resolution.

We're here to support and work with you to overcome any challenges you face using our project. Your continued feedback and participation are essential to our community's success.

Thank you once again for your contribution. I look forward to your update and am here to assist with any further questions or issues you might have.

Best regards,

Steve

**Comment by swade1987** [comment]
@adampayz @joivo I highly recommend uploading an SSH key for a user to bitbucket and leveraging that.

See the provider documentation [here](https://registry.terraform.io/providers/DrFaust92/bitbucket/latest/docs/resources/ssh_key) for more information.

As from all my research, the Bitbucket terraform providers on offer don't allow you to configure repository deploy keys to the specification to work like you can with GitHub and GitLab.
