### ISSUE TITLE
Github Enterprise Questions

### ISSUE THREAD

**Issue by linuxbsdfreak** [fluxcd/terraform-provider-flux#45]
Hi @phillebaba,

I am trying to use the provider with GitHub Enterprise with the provider. I observed the following

- The flux components are correctly installed in flux-system 👍 
- Using the example i modified to run it on GHE under my owner account. It does not work. Is this working only under Github Enterprise organization? 
- My GHE instance does not have ssh access enabled. Therefore i am using https connection which works with the flux command during the bootstrap phase 

```
flux bootstrap github --context=staging--owner=${GITHUB_USER} --repository=${GITHUB_REPO} --token-auth --hostname=github.internal.repo --branch=master --personal --path=clusters/staging
```

Does the provider support this kind of setup ? 

Kevin

**Comment by phillebaba** [comment]
I have never used GitHub Enterprise so I am unsure about the differences between it and "normal" GitHub.

@stefanprodan do you know if there is anything special that has to be done for flux to work with GHE?

**Comment by linuxbsdfreak** [comment]
@phillebaba . Actually looks like that github provider in general does not create repos under owner account.   I have not tested this under github.com. I opened a below ticket. 

https://github.com/terraform-providers/terraform-provider-github/issues/607

Is there any thing that has to be done regarding point 3  ?

**Comment by stefanprodan** [comment]
@linuxbsdfreak the example here https://github.com/fluxcd/terraform-provider-flux#example-usage for a https example.

**Comment by stefanprodan** [comment]
I would close this issue as it's not related to Flux but GitHub, our provider only generates Kubernetes manifests.

**Comment by linuxbsdfreak** [comment]
ok thx @stefanprodan @phillebaba  . Yes i tested it out with github.com account and works fine. With GHE it only works with github provider github = "~> 2.9.2" for repo creation under organization. I still need to verify it with flux at my end.

**Comment by phillebaba** [comment]
I will close this issue as it does not seem like the error was in the provider. If you find any new problems @linuxbsdfreak we can reopen the issue.
