### ISSUE TITLE
First path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by martinnirtl** [fluxcd/terraform-provider-flux#452]
Hi team 👋 

I was just testing `terraform-provider-flux` v1.0.0-rc.1 using the configuration below (identical to the getting started in README) and stumbled across a bug in the provider (automatically reported by Terraform itself). 

`terraform version` output:
```
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/fluxcd/flux v1.0.0-rc.1
+ provider registry.terraform.io/hashicorp/aws v4.63.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

This is my terraform configuration:
```hcl
provider "flux" {
  kubernetes = {
    config_path = "${path.module}/kubeconfig.yaml"
  }

  git = {
    # github_url = "git@github.com:martinnirtl/control-repo.git"
    url = var.github_url
    ssh = {
      private_key = file("${path.module}/flux-bootstrap.pem")
      username    = "git"
    }
  }
}

resource "flux_bootstrap_git" "cluster" {
  path           = "clusters/${var.cluster_name}"
  network_policy = true
  # kustomization_override = file("${path.module}/flux/kustomization.yaml")
}
```

`terraform apply` output:
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Value Conversion Error
│
│   with provider["registry.terraform.io/fluxcd/flux"],
│   on terraform.tf line 23, in provider "flux":
│   23: provider "flux" {
│
│ An unexpected error was encountered trying to convert the Terraform value. This is always an error in the provider. Please report the following to the provider developer:
│
│ parse "git@github.com:martinnirtl/control-repo.git": first path segment in URL cannot contain colon
╵
╷
│ Error: Configuration Read Error
│
│   with provider["registry.terraform.io/fluxcd/flux"],
│   on terraform.tf line 28, in provider "flux":
│   28:   git = {
│   29:     url = var.github_url
│   30:     ssh = {
│   31:       private_key = file("${path.module}/flux-bootstrap.pem")
│   32:       username    = "git"
│   33:     }
│   34:   }
│
│ An unexpected error was encountered trying to convert an attribute value from the configuration. This is always an error in the provider. Please report the following to the provider developer:
│
│ Error: parse "git@github.com:martinnirtl/control-repo.git": first path segment in URL cannot contain colon
```

After prefixing `github_url` variable with `ssh://` (`ssh://git@github.com:martinnirtl/control-repo.git`), i get the following output: 
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Value Conversion Error
│
│   with provider["registry.terraform.io/fluxcd/flux"],
│   on terraform.tf line 23, in provider "flux":
│   23: provider "flux" {
│
│ An unexpected error was encountered trying to convert the Terraform value. This is always an error in the provider. Please report the following to the provider developer:
│
│ parse "ssh://git@github.com:martinnirtl/control-repo.git": invalid port ":martinnirtl" after host
╵
╷
│ Error: Configuration Read Error
│
│   with provider["registry.terraform.io/fluxcd/flux"],
│   on terraform.tf line 28, in provider "flux":
│   28:   git = {
│   29:     url = var.github_url
│   30:     ssh = {
│   31:       private_key = file("${path.module}/flux-bootstrap.pem")
│   32:       username    = "git"
│   33:     }
│   34:   }
│
│ An unexpected error was encountered trying to convert an attribute value from the configuration. This is always an error in the provider. Please report the following to the provider developer:
│
│ Error: parse "ssh://git@github.com:martinnirtl/control-repo.git": invalid port ":martinnirtl" after host
```

**Comment by seanmcguigan** [comment]
I believe it should be ```"ssh://git@github.com/martinnirtl/control-repo.git"``` not ```"ssh://git@github.com:martinnirtl/control-repo.git"```

**Comment by martinnirtl** [comment]
> I believe it should be `"ssh://git@github.com/martinnirtl/control-repo.git"` not `"ssh://git@github.com:martinnirtl/control-repo.git"`

No, this way it wouldn't be a valid ssh url. Also, mine is exactly what i got from GitHub copy.

**Comment by phillebaba** [comment]
@seanmcguigan you are correct.

@martinnirtl the shorter syntax style is not supported in Flux.
https://fluxcd.io/flux/components/source/gitrepositories/#url

**Comment by swade1987** [comment]
Hello @martinnirtl ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by martinnirtl** [comment]
Hey Steve!
I think this issue is good to be closed! Thanks for the reminder and thanks to @phillebaba and @seanmcguigan for providing the answer!! Sorry for not getting back to you guys!
