### ISSUE TITLE
Add ignore field support 

### ISSUE THREAD

**Issue by guyguy333** [fluxcd/terraform-provider-flux#456]
Hi,

Currently, we can't set `ignore` field of `GitRepository`. It would be useful to add this field as a parameter of `flux_bootstrap_git` resource.

Thanks

**Comment by phillebaba** [comment]
We limit the provider to the same configuration parameters that are available in the CLI. I suggest you have a look at the [Customizing Flux](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git#customizing-flux) docs for inspiration how your use case could be achieved.

**Comment by guyguy333** [comment]
Thanks @phillebaba, fixed using kustomisation :)
