### ISSUE TITLE
Can't import flux_bootstrap_git in new provider

### ISSUE THREAD

**Issue by annaken** [fluxcd/terraform-provider-flux#469]
I'm trying to re-write our terraform to use the new flux provider, but when I try to import the flux_bootstrap_git resource I get
```
terraform import flux_bootstrap_git.this flux-system
Error: Could not get GitRepository flux-system/flux-system
```
If I change this to be the name of the git repo I get
```
terraform import flux_bootstrap_git.this my-repo
Error: Could not get Deployment my-repo/kustomize-controller
```

I assume I've done something wrong with the providers/config, but I can't work out what.

```
provider "flux" {
  kubernetes = {
    host                   = "https://api.my-cluster.com"
    client_certificate     = XXX
    client_key             = XXX
    cluster_ca_certificate = XXX
  }
  git = {
    url = "ssh://git@github.com/my-owner-name/my-repo.git"
    ssh = {
      username    = "git"
      private_key = tls_private_key.this.private_key_pem
    }
  }
}
provider "github" {
  owner = "my-owner-name"
}
```
and
```
resource "flux_bootstrap_git" "this" {
  cluster_domain   = "my-cluster"
  components_extra = ["image-reflector-controller", "image-automation-controller"]
  depends_on       = [github_repository_deploy_key.this]
  path             = "cluster/flux"
}
```

**Comment by phillebaba** [comment]
The value that you pass at the end of the import command is the namespace that Flux is installed in, as stated in the documentation. I am trying to figure out where `kubeconf`` is coming from.

**Comment by annaken** [comment]
Ah right so kubeconf is the name of the repo. Let me update the original post for clarity.

**Comment by phillebaba** [comment]
What version of Flux is installed compared to the version of the provider that you are using?

**Comment by annaken** [comment]
I upgraded this cluster first before I tried to move over to the new provider layout.
Flux version is 2.0.0-rc2, and provider version is 1.0.0-rc.2
