### ISSUE TITLE
What api versions are expected?

### ISSUE THREAD

**Issue by adeturner** [fluxcd/terraform-provider-flux#473]
I originally raised [#3905](https://github.com/fluxcd/flux2/issues/3905) as I was getting bootstrap error: ```no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"```

I cloned https://github.com/fluxcd/flux2-kustomize-helm-example as a start point

I didnt specify a provider version and it installed terraform-provider-flux_v0.25.3

```
terraform {
...
    flux = {
      source = "fluxcd/flux"
    }
}
```

I traced the issue to the fact that the TF provider installs v1beta API versions. 

After I changed all references from

```apiVersion: kustomize.toolkit.fluxcd.io/v1```
to
```apiVersion: kustomize.toolkit.fluxcd.io/v1beta2```

it worked

Is this expected behavior?  What should I be using...

```
$ k api-resources | grep flux
helmreleases                      hr                  helm.toolkit.fluxcd.io/v2beta1           true         HelmRelease
kustomizations                    ks                  kustomize.toolkit.fluxcd.io/v1beta2      true         Kustomization
alerts                                                notification.toolkit.fluxcd.io/v1beta2   true         Alert
providers                                             notification.toolkit.fluxcd.io/v1beta2   true         Provider
receivers                                             notification.toolkit.fluxcd.io/v1beta2   true         Receiver
buckets                                               source.toolkit.fluxcd.io/v1beta2         true         Bucket
gitrepositories                   gitrepo             source.toolkit.fluxcd.io/v1beta2         true         GitRepository
helmcharts                        hc                  source.toolkit.fluxcd.io/v1beta2         true         HelmChart
helmrepositories                  helmrepo            source.toolkit.fluxcd.io/v1beta2         true         HelmRepository
ocirepositories                   ocirepo             source.toolkit.fluxcd.io/v1beta2         true         OCIRepository
```

**Comment by phillebaba** [comment]
The rc versions of the provider uses the rc versions of Flux, which upgrades some CRD versions. Could you go into more detail what you issue is?

**Comment by adeturner** [comment]
@phillebaba thanks for the reply. Worth mentioning I've previously been an architect so I'm learning some new detail right now

A. Does the answer lie in my overall choice of versions, which possibly should ideally match?
- flux client: 2.0.0-rc.3
- terraform-provider-flux_v0.25.3 (default download)
- k8s 1.25.6

B. Issues:

1) There does not appear to be any doc discussing the compatibility of api version to flux product version so was looking for clarity
2) For me, the api versions of https://github.com/fluxcd/flux2-kustomize-helm-example do not work out of the box with the default terraform provider v0.25.3. I had to downgrade the example.
3) I've not worked out the way of working. Sometimes when I re-run terraform plan, I'm often seeing the plugin downgrade from v1 to v1beta.
4) Sometimes I'm having to flux uninstall/flux bootstrap to solve problems. This might be related to A and B.3

**Comment by stefanprodan** [comment]
@adeturner you need to use TF RC.3 to match the latest release. RCs are the same as v0 in semver terms, anyway this will be sorted out when we do 2.0 GA.

**Comment by adeturner** [comment]
Thanks @stefanprodan, will give it a go

**Comment by adeturner** [comment]
Thanks @stefanprodan @phillebaba , TF provider is working much better with respect to versions
