### ISSUE TITLE
Support for `--branch`?

### ISSUE THREAD

**Issue by oscar-b** [fluxcd/terraform-provider-flux#475]
Is it possible to specify the branch to follow when using `flux_bootstrap_git`? 

The `--branch` option for `flux bootstrap`
https://fluxcd.io/flux/cmd/flux_bootstrap/

**Comment by stefanprodan** [comment]
We support all options available in `flux bootstrap git`, the Git ones documented here https://registry.terraform.io/providers/fluxcd/flux/latest/docs#nested-schema-for-git

**Comment by oscar-b** [comment]
Hm thanks, somehow I thought that was the target branch for the provider.
