### ISSUE TITLE
1.0.0-rc.4 did not update default Flux version

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/terraform-provider-flux#486]
There is a list of places where the Flux version is updated each release, and it looks like yesterday's release missed a few:

https://github.com/fluxcd/terraform-provider-flux/commit/c2a2db7a8f570510d43989a8f1d14c34708edab3 - the release commit for 1.0.0-rc.3
vs
https://github.com/fluxcd/terraform-provider-flux/commit/d31bb4b468c03d84ae174d5ecdf787cbbe4e760a - the release commit for 1.0.0-rc.4

Should we add some `make version-set` like is used in podinfo, that scans for the current version number, uses sed for string substitutions, and then document the use of this for the provider's release process?

A separate issue maybe, I couldn't find any detailed internal or developer docs for releasing the provider where we would add this script to the instructions.

**Comment by stefanprodan** [comment]
Yeah we missed some changes https://github.com/search?q=repo%3Afluxcd%2Fterraform-provider-flux%20v2.0.0-rc.3&type=code cc @darkowlzz
