### ISSUE TITLE
Need to be able to specify Kustomization and GitRepository names

### ISSUE THREAD

**Issue by annaken** [fluxcd/terraform-provider-flux#494]
I see that here

https://github.com/fluxcd/terraform-provider-flux/blob/main/internal/provider/resource_bootstrap_git.go#L800-L819

it is expected that the Kustomizaton and GitRepository names are expected to be the same as the namespace, which defaults to flux-system.

The namespace we use *is* flux-system, but our Kustomization is called "flux" and GitRepository is called "kubeconf". 

We need to be able to pass these values into the provider - currently I am unable to import our existing setup to the new provider.

**Comment by stefanprodan** [comment]
This is not supported, the TF provider must follow the Flux CLI convention.

**Comment by annaken** [comment]
But OK, I can re-name the flux-system Kustomization and GitRepository, but I'm slightly terrified of the impact.
Am I correct in thinking that if I pause both first, and then rename (ie create new and delete old) that should be safe?

**Comment by stefanprodan** [comment]
You suspend them both, and Flux will not prune any resources

**Comment by annaken** [comment]
Will try. Thanks :)
