### ISSUE TITLE
Need to be able to specify spec/ignore and kustomization interval

### ISSUE THREAD

**Issue by annaken** [fluxcd/terraform-provider-flux#495]
Hi, I'm just switching us over to use the new provider, but there are a couple of configuration settings missing for our needs:

1. The GitRepository ignore setting
2. The Kustomization interval setting

Not a huge deal, but it means that after running the provider, I then have to go back into gotk-sync.yaml and edit the file back to how we want it.

**Comment by stefanprodan** [comment]
You can patch the flux-system spec using kustomize override, docs here https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git#customizing-flux

**Comment by annaken** [comment]
Ohhh yes! We already do that for gotk-components. Great, thanks!
