### ISSUE TITLE
Provider doesn't update URL of source objects

### ISSUE THREAD

**Issue by ldunkum** [fluxcd/terraform-provider-flux#499]
We recently migrated our flux repositories from GitLab to GitHub and updated the URL in the flux provider block, expecting it to change the `spec.url` field of the flux-system GitRepository.

Provider version: 0.25.3

terraform plan output:

```diff
  # flux_bootstrap_git.main will be updated in-place
  ~ resource "flux_bootstrap_git" "main" {
        id                     = "flux-system"
      ~ repository_files       = {
          ~ "clusters/digital-playground/flux-system/gotk-sync.yaml"       = <<-EOT
                # This manifest was generated by flux. DO NOT EDIT.
                ---
                apiVersion: source.toolkit.fluxcd.io/v1beta2
                kind: GitRepository
                metadata:
                  name: flux-system
                  namespace: flux-system
                spec:
                  interval: 1m0s
                  ref:
                    branch: main
                  secretRef:
                    name: flux-system
              -   url: ssh://git@gitlab.com/group/repo.git
              +   url: ssh://git@github.com/org/repo.git
```

After applying, the GitRepository resource still had the old URL and had to be manually tainted and recreated.

**Comment by ldunkum** [comment]
Hi Steve,

thanks for your reply, I'm on vacation at the moment and can't access my work computer to check. 
I'll report back in the second week of April.

Cheers

**Comment by hirenko-v** [comment]
@swade1987 It applies for us as well. We are trying to change [branch](https://registry.terraform.io/providers/fluxcd/flux/latest/docs#branch)

I see commit to the repo in the new branch but nothing is changed in kubernetes GitRepository custom resource

**Comment by swade1987** [comment]
@hirenko-v sorry about the late reply, just for clarification does this still happen with the latest version of the provider?

**Comment by hirenko-v** [comment]
@swade1987, yes we use v1.2.3

**Comment by swade1987** [comment]
I think it might be an issue because the flux instance running in the cluster is still pointing at the old branch.

@stefanprodan  is there a way with flux bootstrap to force a sync pushing the changes to git into the cluster after the first bootstrap has already taken place?

**Comment by swade1987** [comment]
@ldunkum @hirenko-v in this case you would need to run `terraform destroy` and `terraform apply` again to force the "bootstrap" process to occur again.

**Comment by hirenko-v** [comment]
@swade1987 @stefanprodan , that is some kind of nonsense, flux cli allows to re-botstrap an existing instance. Why tf provider pushes just commit to repo but does not do changes in k8s then?

**Comment by stefanprodan** [comment]
@hirenko-v see #661

**Comment by ldunkum** [comment]
@swade1987 @stefanprodan thanks for the input.

**Comment by stefanprodan** [comment]
Test this with #661 and it works
