### ISSUE TITLE
SSH handshake failed and unable to authenticate

### ISSUE THREAD

**Issue by ocni-dtu** [fluxcd/terraform-provider-flux#514]
Hi guys,

I cannot bootstrap Flux with a GitHub repo.
Before this step I have ran `terraform apply -target tls_private_key.flux` as suggested in this [issue](https://github.com/fluxcd/terraform-provider-flux/issues/395)
I'm getting the following error, running `terraform apply`:
```
│ Error: Git Client
│ 
│ could not clone git repository: unable to clone 'ssh://git@github.com/gdtt-sustainability/gitops.git': ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
My PAT has `repo` scope and I'm admin of the repo.
I'm using v1.0.0 of the flux terraform provider.
This is my setup:
```
resource "tls_private_key" "flux" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P256"
}

provider "flux" {
  kubernetes = {
    host                   = data.azurerm_kubernetes_cluster.aks.kube_config.0.host
    client_certificate     = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.client_certificate)
    client_key             = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.cluster_ca_certificate)
  }
  git = {
    url = "ssh://git@github.com/${var.flux_github_org}/${var.flux_github_repository}.git"
    ssh = {
      username    = "git"
      private_key = tls_private_key.flux.private_key_pem
    }
  }
}

provider "github" {
  owner = var.flux_github_org
  token = var.flux_github_token
}

resource "github_repository_deploy_key" "this" {
  title      = "Flux"
  repository = var.flux_github_repository
  key        = tls_private_key.flux.public_key_openssh
  read_only  = "false"
}

resource "flux_bootstrap_git" "flux_system" {
  depends_on = [github_repository_deploy_key.this]

  path = var.flux_target_path
  components_extra = [
    "image-reflector-controller",
    "image-automation-controller"
  ]
}
```

Where is it that I go wrong?

**Comment by ocni-dtu** [comment]
I've cleared the state and got it to work that way

**Comment by avnes** [comment]
I ran into the same issue today, and managed to find an ugly workaround to this, but still less ugly than to clear all state. Basically this can happen if you create a new Personal Access Token and retired the old one. In which case, all deploy keys created with that PAT gets deleted.

Find the current deploy key in state:
`terraform state show github_repository_deploy_key.main`

Use output from this to create the deploy key manually in the GitHub repo as the user that owns the Personal Access Token (PAT)

Remove the old deploy key from state:
`terraform state rm github_repository_deploy_key.main`

Find all deploy keys in your repo:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <PAT>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/keys
```

Find the ID for the deploy key you created manually, and the import it to Terraform:

`terraform import github_repository_deploy_key.main REPO:<ID>`

**Comment by LittaKake** [comment]
I had this issue when I forgot to add the username in the `ssh` spec.

**Comment by awdv00** [comment]
if you manage the gitlab deploy key via the gitlab provider, e.g.:
```terraform
resource "github_repository_deploy_key" "this" {
  title      = "Flux"
  repository = var.flux_github_repository
  key        = tls_private_key.flux.public_key_openssh
  read_only  = "false"
}
```

you can simply adjust the name; this will destroy and re-create it on gitlab. afterwards, it started working for me again.
