### ISSUE TITLE
Expanding Authentication Support for GitHub

### ISSUE THREAD

**Issue by mcantinqc** [fluxcd/terraform-provider-flux#521]
The latest version of FluxCD provider has limited authentication options, allowing only SSH key or Username/Password for git authentication. In contrast, the previous version allowed us to utilize any provider of our preference, such as the official GitHub provider (https://registry.terraform.io/providers/integrations/github/latest/docs), which supported GitHub-specific authentication methods like PAT or app_auth.

The absence of support for these GitHub-specific authentication methods is seen as a step backward for me.

**Comment by stefanprodan** [comment]
You can pass the deploy key (SSH private key file) that you’ve generated with the GitHub provider to Flux and it will create the secret for you.

**Comment by TomBillietKlarrio** [comment]
That are indeed workarounds. But our current pipeline has no permissions to generate deploy keys, and we'd like to keep it that way. So just being able to use tokes like we currently do would be useful.

**Comment by swade1987** [comment]
@mcantinqc I have created an example of using a PAT with the `flux_bootstrap_git` resource available [here](https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github-via-pat) does this resolve your issue or are looking for something else?
