### ISSUE TITLE
Downtime during Flux upgrades

### ISSUE THREAD

**Issue by thomas-parrish-axi** [fluxcd/terraform-provider-flux#523]
Hello,
Whenever our flux instance upgrades it uninstalls all the application code, and reinstalls it using the latest version of the CRDs. The terraform we are using to do the install uses the `flux_install` and `flux_sync` data sources. These uninstall and reinstall all our application code during upgrades, which causes an extended outage. This appears to be because all the git repositories are removed and then created again, causing Flux to trigger reconciliation on all installed code.

If we switch to `flux_bootstrap_git` has this been addressed, or will we still see the same behaviour?

**Comment by stefanprodan** [comment]
Using `flux_bootstrap_git` the upgrade is seamless, no reconciled apps are touched.

**Comment by swade1987** [comment]
@stefanprodan I think we can close this.
