### ISSUE TITLE
Support for branch

### ISSUE THREAD

**Issue by afnan** [fluxcd/terraform-provider-flux#539]
I am trying to get a specific branch instead of working on main. I was able to do this with simple bootstrap command but not in terraform 

```
# Flux bootstrap configuration
resource "flux_bootstrap_git" "this" {
  depends_on = [gitlab_deploy_key.this]
  branch     = var.gitlab_branch
  path       = "environments_v125/development"
}
```

```
│ Error: Unsupported argument
│ 
│   on flux_dev.tf line 99, in resource "flux_bootstrap_git" "this":
│   99:   branch     = var.gitlab_branch
│ 
│ An argument named "branch" is not expected here.
```

**Comment by stefanprodan** [comment]
The `branch` is a property of `git`, see here the documentation: https://registry.terraform.io/providers/fluxcd/flux/latest/docs#schema

**Comment by hirenko-v** [comment]
@stefanprodan If branch is changed in git section how could we update it in kubernetes, suums like after anther rerraform apply it is not changed in kubernetes

**Comment by arm-moodys** [comment]
> @stefanprodan If branch is changed in git section how could we update it in kubernetes, suums like after anther rerraform apply it is not changed in kubernetes

after the terraform apply, on the command line run:

```bash
flux reconcile source git flux-system --verbose && flux reconcile kustomization flux-system
````

you should see:

```bash
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision NEW_BRANCH@sha1:LATEST_SHA_FROM_NEW_BRANCH
```
