### ISSUE TITLE
Flux provider doesn't push to git at apply

### ISSUE THREAD

**Issue by cebidhem** [fluxcd/terraform-provider-flux#55]
Hey there, 

Reading the docs for FluxV2, when I do bootstrap from the CLI, all the flux manifests are pushed to the git repository in order to self-managed itself from Git. 
As far as I experienced, the terraform provider doesn't behave this way (no manifest committed/pushed to `target_path`).

I'd assume it is the expected behaviour since upgrade should be triggered by the `terraform apply`, but still in the docs it says here https://toolkit.fluxcd.io/guides/installation/#terraform-upgrade:
```
Update the Flux provider to the latest release and run terraform apply.

Tell Flux to upgrade itself in-cluster or wait for it to pull the latest commit from Git
```
Is it a mismatch in the doc ? I mean, since there is no git push at initial `tf apply`, it is the actual `tf apply` that would upgrade Flux right ?

**Comment by stefanprodan** [comment]
Git push is not the Flux provider concern, here is a GitHub example: https://github.com/fluxcd/terraform-provider-flux/blob/main/examples/github/main.tf

**Comment by cebidhem** [comment]
Ok I understand now I have to find a way to push those files to Gitlab somehow.

Thanks for the quick clarification

**Comment by stefanprodan** [comment]
You may want to take a look at https://github.com/fluxcd/terraform-provider-flux/pull/43

**Comment by cebidhem** [comment]
Hey @stefanprodan actually I've looked at it, and Gitlab APIs to commit a file and manage to do so. 
Quite unfriendly because GitLab APIs don't really allow to call at the same time for the 3 files, so can't really use a `for_each` here. And you have to run first time with the `create` action, then with `update` action for the future runs.
And we have to write the b64 encoded content in a file because otherwise the payload it just too big.

But I find weird to have to write almost 200 lines of tf code for GitLab users, when actually the CLI takes care of the pushing for us.
I guess I'm interested on why you chose not to reproduce with the provider the way it is currently working with the CLI ?

I'm even considering downloading flux-cli in my runner's image to be able to use a `local-exec` that will basically `flux bootstrap gitlab`

**Comment by phillebaba** [comment]
Hopefully I can shed some light on the reasoning. 

In theory yes, we could build a full resource that would do everything for us, apply the resources to cluster, wait for them to start, and commit to git just like the CLI does. Doing this would go against the whole point of Terraform, as we would have to re-implement what has already been done by other providers. I also think it would be a bit difficult to do as the Terraform SDK can sometimes be a bit difficult to work with. The provider basically implements CRUD functions and then it is up to Terraform core to determine if a resource should be replaced and created or updated in place or left alone.

We dont have the same examples for GitLab as we do for GitHub as the GitLab provider currently does not implement a repository file resource yet. I was aware of this when building the provider and was hoping that someone would implement this soon. A quick look around in the provider turns up that someone is working on the resource that you need. When that gets merged and a new version gets released I will create an example for GitLab.
https://github.com/gitlabhq/terraform-provider-gitlab/pull/350

Lets hope that happens soon :smiley:

**Comment by cebidhem** [comment]
Hey @phillebaba thanks for explaining motivations here. And indeed you're right saying it is - on my case and probably others too - because Gitlab doesn't provide this I'd assume basic resource `repository_file`.

It is the frustrating part because it forces us to create a long list of `null_resource` and `local-exec` and in my opinion, if I have to do that many `local-exec` then it doesn't make sense to even use terraform.

Anyway, thanks for the link to the PR I didn't manage to find it 😄 I'll monitor it!
