### ISSUE TITLE
Bootstrap with Bucket source solution with flux_install deprecated

### ISSUE THREAD

**Issue by suyuee** [fluxcd/terraform-provider-flux#551]
Our setup is kind of special in that we don't want to sync with GitRepo at all and instead we as Bucket as the sole source.

Therefore in our case, the endorsed bootstrap process doesn't make much sense because it doesn't support bootstrap with Bucket.

Is there any recommended way to install flux controllers with terraform? flux_install sounds like a good fit for our case, but seems it's going to be deprecated.

Appreciate any advice in advance :)

**Comment by stefanprodan** [comment]
For install only, you can use the Terraform Helm provided. Docs here: https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/install-helm-release
