### ISSUE TITLE
flux_bootstrap_git "Plugin did not respond" during terraform import

### ISSUE THREAD

**Issue by EishanR** [fluxcd/terraform-provider-flux#570]
We are currently on Flux 0.41.2 and terraform flux/fluxcd provider 0.25.3 and wish to migrate to using the new `flux_bootstrap_git` resource. While running the command `tf import flux_bootstrap_git.this flux-system` we encounter the following error : 

```
The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin logs may cont
        github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/fwserver/server_importresourcestate.go:104 +0x462
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ImportResourceState(0xc0002dba20, {0x20611a0?, 0xc002c6aae0?}, 0xc00062fee0)
        github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/proto6server/server_importresourcestate.go:44 +0x30b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc000698fa0, {0x20611a0?, 0xc00068da40?}, 0xc00399c1e0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:846 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler({0x1c63e80?, 0xc000698fa0}, {0x20611a0, 0xc00068da40}, 0xc000bb4230, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004c41e0, {0x206b378, 0xc0006d61a0}, 0xc0029f7680, 0xc0005162a0, 0x2ff3ef8, 0x0)     
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0004c41e0, {0x206b378, 0xc0006d61a0}, 0xc0029f7680, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-flux_v0.25.3.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

We have decided to migrate to using the new resource and then eventually upgrade to the newer version of flux.  The datasources `flux_install` and `flux_sync` are not yet deprecated in version 0.25.3 Provider

**Comment by kingdonb** [comment]
It's not clear how you get this error without a look at your `tf` files, I have not seen this error before. You mentioned that you want to upgrade to the new version of Flux, I don't know if there is a seamless transition possible between the old and new versions of terraform-provider and their state. I don't think you need to use `terraform import` - flux bootstrap is idempotent so if you bootstrap over an existing bootstrap, it should overwrite it with the same content.

But the bootstrap_git resource belongs to the new provider - what resources exactly are you trying to import?

**Comment by swade1987** [comment]
@EishanR could you provide me the full Terraform configuration you had previously please so I can best advise on next steps.

**Comment by swade1987** [comment]
Hello @EishanR  👋

I hope all is well with you. I'm just reaching out to you as part of our initiative to ensure the quality and responsiveness of our project's issue tracking. Thank you for your previous contributions by reporting issues you've encountered; your engagement is invaluable to the health and progress of our project.

I've reviewed the issue you reported and noted that it involves using supported resources, which is great. However, I also noticed that there has been little activity on this issue lately. We understand that circumstances change and priorities shift, which may affect the urgency or relevance of an issue.

We're implementing a policy regarding inactive issues to keep our project's issue tracker effective and up-to-date. If there's no further activity on this issue within the next 3 weeks, we will mark it inactive and close it. This approach helps us maintain focus on current and actively pursued concerns, ensuring resources are well allocated.

That said, we are still very much interested in resolving the issue you've encountered. If the problem persists or if you have any new information that could help us address it, please don't hesitate to update the issue or comment. Your input could be crucial in finding a resolution. Alternatively, if the issue no longer affects you or has been resolved, let us know so we can close it with the right resolution.

We're here to support and work with you to overcome any challenges you face using our project. Your continued feedback and participation are essential to our community's success.

Thank you once again for your contribution. I'm looking forward to your update and am here to help with any other questions or issues you might have.

Best regards,

Steve
