### ISSUE TITLE
GitHub 409 Could not update file

### ISSUE THREAD

**Issue by Monta89** [fluxcd/terraform-provider-flux#573]
I keep getting the following error using `resource "github_repository_file"` when I apply Terraform 
`Error: PUT https://api.github.com/repos/<ORG>/<REPO>/contents/clusters/<FILE>/<PATH>/flux-system/gotk-components.yaml: 409 Could not update file: Required status check "manifests" is expected. []`

**Comment by swade1987** [comment]
I propose you upgrade to the latest flux terraform provider and leverage the `flux_bootstrap_git` resource. All existing resources are no longer maintained.
