### ISSUE TITLE
destroy on `flux_bootstrap_git` fails if the namespace `flux-system` is not present anymore

### ISSUE THREAD

**Issue by gmembre-zenika** [fluxcd/terraform-provider-flux#574]
Hi, 

Thanks for your work 💪 

When destroying the `flux_bootstrap_git`, if the `flux-system` namespace is not present anymore for any reason, the provider fails with the following error:
```
$ terraform destroy -auto-approve
...
flux_bootstrap_git.this: Destroying... [id=flux-system]

│ Error: Unable to remove namespace
│ 
│ namespaces "flux-system" not found
```

I have to recreate the namespace to help it to destroy it back :-) 

I expect it to not fail as the ressource it try to destroy is already destroyed. This is the case with the `aws` provider for example.

Regards

**Comment by swade1987** [comment]
Could you please provide the following information @gmembre-zenika 

1. The total output from the `terraform version` command in the repository you're executing from.
2. The total configuration of the `flux_bootstrap_git` resource
3. The total configuration of all providers (see below as an example)

```
data "aws_eks_cluster_auth" "cluster" {
  name = module.cluster.cluster.id
}

provider "kubernetes" {
  host                   = module.cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(module.cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

provider "flux" {
  git = {
    url    = "ssh://${var.flux_bootstrap_configuration["git_repo"]}"
    branch = "main"
    ssh = {
      username    = "git"
      private_key = data.terraform_remote_state.keypairs.outputs.flux_ssh_key["private"]
    }
  }
  kubernetes = {
    host                   = module.cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(module.cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}
```

Looking forward to your reply.

**Comment by swade1987** [comment]
@gmembre-zenika destroying the `flux-system` namespace outside of Terraform will cause you much pain. 
Anything managed by Terraform should be left to Terraform to manage. I would propose we close this issue.
