### ISSUE TITLE
Bootstrap with AWS Codecommit using Terraform

### ISSUE THREAD

**Issue by spiquera** [fluxcd/terraform-provider-flux#586]
Hi everyone,
Despite of having a Github and Gitlab bootstrap guides on how to synchronize flux in a cluster with a repository, I wanted to know if it is planned to release an update to make it easier to configure flux with a AWS Codecommit or if someone got the same problem.
The problem is that when trying to configure the flux provider with Terraform, it has some kind of issues with how the public key is managed and used. For now i have this provider configured:

```
 provider "flux" {
  kubernetes = {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

    exec = {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      # This requires the awscli to be installed locally where Terraform is executed
      args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
    }
  }

  git = {
    url = var.create_fluxcd_repository ? aws_codecommit_repository.this[0].clone_url_ssh : var.eks_repository_url
    ssh = {
      username    = aws_iam_user_ssh_key.codecommit_user_ssh_key.ssh_public_key_id
      private_key = tls_private_key.codecommit_ssh_key.private_key_pem
    }
  }
}

resource "flux_bootstrap_git" "this" {
  path = "clusters/develop"
}
```

There is someone who got it working in an easier way? I mean, this solution seems to work if the repository has been initialized manually, but i want to know if someone that is working with Flux and AWS Codecommit got a simpler solution.
Thanks you for your time!

**Comment by swade1987** [comment]
I would highly recommend you check out [this](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html) @spiquera

**Comment by swade1987** [comment]
@spiquera, as this is not an issue but rather a topic for discussion, can I propose you ask this on https://github.com/fluxcd/flux2/discussions please
