### ISSUE TITLE
File permission problems when using `manifests_path` argument of `flux_bootstrap_git` resource

### ISSUE THREAD

**Issue by gfrogat** [fluxcd/terraform-provider-flux#590]
Hi all,

I encounter file permission problems when trying the new [`manifests_path`](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git#manifests_path) argument of the [`flux_bootstrap_git`](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git) resource.

The argument is available since version `1.2.0` and has been added via #503.

## Code Snippets to reproduce

```terraform
# example.tf

terraform {
  required_providers {
    flux = {
      source = "fluxcd/flux"
      version = "1.2.1"
    }
  }
}

provider "flux" {
  kubernetes = {
    config_path = "~/.kube/config"
  }
  git = {
    url = "<your_url>"
    branch = "<your_branch>"
    
    # configure credentials
  }
}

resource "flux_bootstrap_git" "this" {
  path = "<your_cluster_path>"
  
  manifests_path = "${path.cwd}/manifests"
}
```

```bash
# setup folder + kustomization

mkdir manifests
curl -LO https://github.com/fluxcd/flux2/releases/download/v2.2.1/manifests.tar.gz
tar xzf manifests.tar.gz -C manifests
	
cat <<EOF > manifests/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-controller.yaml
  - image-automation-controller.yaml
  - image-reflector-controller.yaml
  - kustomize-controller.yaml
  - notification-controller.yaml
  - policies.yaml
  - rbac.yaml
  - source-controller.yaml
EOF
```

## Error

```
flux_bootstrap_git.this: Creating...
╷
│ Error: Bootstrap run error
│ 
│   with flux_bootstrap_git.this,
│   on example.tf line 25, in resource "flux_bootstrap_git" "this":
│   25: resource "flux_bootstrap_git" "this" {
│ 
│ component manifest generation failed: open /gotk-components.yaml: read-only file system
╵
```

---

First of all the documentation of this feature is not very clear. I was quite confused why it would require its own kustomization and not only the path to a local `manifests.tar.gz` file.

> [`manifests_path`](https://registry.terraform.io/providers/fluxcd/flux/1.2.2/docs/resources/bootstrap_git#manifests_path) (String) The install manifests are built from a GitHub release or kustomize overlay if using a local path. Defaults to https://github.com/fluxcd/flux2/releases.

It was necessary to have a deep dive into the flux internals to understand what's going on.

## Explanation

If configured `manifests_path` will update the variable `baseURL` which is returned as part of `installOptions` within the `flux_bootstrap_git` terraform resource: 

https://github.com/fluxcd/terraform-provider-flux/blob/b517039456e8d9a1f6609dc9621c100c303595f4/internal/provider/resource_bootstrap_git.go#L960-L963

(the defaults for these options are configured in the main `fluxcd/flux2` repo `L53` https://github.com/fluxcd/flux2/blob/20fbcfadac03ea0b8c0c698d5b4d64b61e15df74/pkg/manifestgen/install/options.go#L41-L60).

`baseURL` is then used again in the `manifestgen.install.Generate` function during component reconciliation:
https://github.com/fluxcd/flux2/blob/20fbcfadac03ea0b8c0c698d5b4d64b61e15df74/pkg/manifestgen/install/install.go#L51-L70 (for some reason GitHub doesn't want to render this as codeblock as part of the issue so I copied the code snippet here ...)

```go
        if !strings.HasPrefix(options.BaseURL, "http") {
                if err := build(options.BaseURL, output); err != nil {
                        return nil, err
                }
        } else {
                // download the manifests base from GitHub
                if manifestsBase == "" {
                        manifestsBase, err = manifestgen.MkdirTempAbs("", options.Namespace)
                        if err != nil {
                                return nil, fmt.Errorf("temp dir error: %w", err)
                        }
                        defer os.RemoveAll(manifestsBase)
                        output, err = securejoin.SecureJoin(manifestsBase, options.ManifestFile)
                        if err != nil {
                                return nil, err
                        }
                        if err := fetch(ctx, options.BaseURL, options.Version, manifestsBase); err != nil {
                                return nil, err
                        }
                }


                if err := generate(manifestsBase, options); err != nil {
                        return nil, err
                }


                if err := build(manifestsBase, output); err != nil {
                        return nil, err
                }
        }
```

By default (i.e. `baseURL` set to GitHub Releases) flux would use the `else` codepath of the if-statement, create a temporary directory and then [`fetch`](https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/manifests.go#L37) the `manifests.tar.gz` file from the GitHub releases, [`generate`](https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/manifests.go#L68) a new kustomization with templated files (see: https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/templates.go) and then run [`build`](https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/manifests.go#L125) and output the results to the file `output` which is configured via `options.ManifestFile` and set to `gotk-components.yaml` by default.

When using a `baseURL` which does not start with `http` (e.g. via `manifest_path`) the first codepath of the if-statement is taken, no temporary directory is created and only [`build`](https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/manifests.go#L125)  is run, generating `/gotk-components.yaml` which causes the error.

## Problems

- not using temporary directory when using custom `baseURL`: this causes my file permission problem, because flux wants to create the built kustomization in the root filesystem
- no `generate` function when using custom `baseURL`: this makes this feature cumbersome to use via Terraform because one has to supply their own kustomization which is currently not documented. Another problem is that all other arguments from the terraform resource are now also ignored because we skip the templating step where they would usually be configured

From my point of view the current interface for `manifests_path` is not ideal and should be reviewed. IMO simple URL support as already suggested here https://github.com/fluxcd/terraform-provider-flux/issues/529 and support for local `manifests.tar.gz` file would be preferable but integrating this would also require changes in the `fluxcd/flux2` repo.

edit: typos

**Comment by swade1987** [comment]
@gfrogat, could you tell me what you are trying to achieve here, please?

Are you wanting to deploy additional resources (e.g. `Gitrepository`)  to the cluster during the bootstrap process?

**Comment by kcighon** [comment]
we have the same issue - our terraform runs in an unprivileged docker container which does not have permissions on `/`

**Comment by kcighon** [comment]
> same issue here.
> 
> 
> 
> ` component manifest generation failed: open /gotk-components.yaml: permission denied`

I had this in my docker image - work around was to pre-create the file (empty) in root with appropriate permissions.
