### ISSUE TITLE
Please support install & uninstall functionality similar to flux cli 

### ISSUE THREAD

**Issue by maximveksler** [fluxcd/terraform-provider-flux#594]

**Comment by swade1987** [comment]
@maximveksler, can you explain actually what you mean here, please? With the `flux_bootstrap_git` resource you can bootstrap a cluster using `terraform apply` and uninstall flux from a cluster using `terraform destroy`

**Comment by maximveksler** [comment]
@swade1987 `flux install` allows deploying the flux controllers into the cluster without provisioning them from git. 

For our workflow we using a fleet approach where flux is deployed into the cluster using terraform. I do not wish to provising a git repo for each cluster, instead I need to be able to deploy flux directly. 

Currently I'm using flux2 Helm chart as the workaround, however being able to do that from the terraform provider directly would be much better approach for that. 

Hopefully that makes the requirement clearer.

**Comment by swade1987** [comment]
@maximveksler take a look at https://github.com/swade1987/flux2-multi-cluster-bootstrap-repo I think it shows what you're trying to achieve. It shows how you can bootstrap all clusters from the same GitHub repo and making sure the same GitRepositories and Kustomizations land in the cluster.

I've used it in numerous companies in the past. Any questions about it please let me know.

**Comment by maximveksler** [comment]
@swade1987 as explained, the requirement is to be able deploy flux without referencing a git repo. 

The example you've provided allows composing environment using a shared git repo, where for each new cluster terraform_flux_proviser will perform a commit operation. That is not the use case, the main reason being sharing a git repo does not allow isolation of spec between fleet clusters (same git repo source is available for ALL fleet clusters).

**Comment by swade1987** [comment]
@maximveksler makes sense in that case the v2 helm chart is your best bet. Could you please close the issue for me please (I don't have the access to do this yet).

**Comment by maximveksler** [comment]
Excuse me, why should the issue be closed if the request is for adding missing functionality to the provider?

**Comment by swade1987** [comment]
The provider is used to bootstrap a cluster from scratch using the `flux_bootstrap_git` resource. If that is not what users want, leveraging the upstream flux v2 helm chart via Terraform is the recommended approach.

**Comment by stefanprodan** [comment]
This provider is for running the equivalent of `flux bootstrap` command, we have no plans on expanding its scope beyond that. If you don't want to bootstrap, then the only way to install Flux from Terraform it by using https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/helm-install
