### ISSUE TITLE
Update git password in terraform should update git password in kubernetes too

### ISSUE THREAD

**Issue by pschirch** [fluxcd/terraform-provider-flux#596]
Hey,

we auto rotate our git password in flux provider config.

```tf
provider "flux" {
  ...
  git = {
    ...
    http = {
      username = "token"
      password = var.flux_gitlab_token
    }
  }
}
```

Terraform performs the autorotate as expected, but the flux provider does not recognize that change of `var.flux_gitlab_token`. Cause this, flux could not interact with the corresponding git infrastructure repository.

The flux provider should recognize that change of `var.flux_gitlab_token` and keep it up to date in the cluster by upgrading the necessary secret.

Currently we use the following workaround.

1. Uninstall flux from cluster (by remove `flux_bootstrap_git` resource).
2. Rotate `var.flux_gitlab_token`.
3. Install flux in cluster (by add `flux_bootstrap_git` resource).

**Comment by swade1987** [comment]
@pschirch unfortunately this is not possible. As documented here [https://fluxcd.io/flux/installation/bootstrap/gitlab/#gitlab-deploy-keys] people need to delete the `flux-system` secret for it to be recreated. 

My recommended option would be to create and manage the secret flux uses in Terraform directly and not via the bootstrap process. See @stefanprodan comment [here](https://github.com/fluxcd/terraform-provider-flux/issues/547#issuecomment-2043673290) for this.
