### ISSUE TITLE
Add resource documentation

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/terraform-provider-flux#6]
The data sources in the provider need documentation describing the different parameters. This is extra important as it is also used in the registry to display detailed information. The documentation should follow the standards described by the Terraform docs.

https://www.terraform.io/docs/registry/providers/docs.html

**Comment by redeux** [comment]
There is a registry doc generator available here: https://github.com/hashicorp/terraform-plugin-docs

**Comment by phillebaba** [comment]
I will close this as we have merged the initial setup of documentation. From now on all new changes will have to make sure that the docs have been updated and generated.

Thank you @redeux for the help getting things started with the docs!
