### ISSUE TITLE
Support `commit_message_appendix` attribute

### ISSUE THREAD

**Issue by timofurrer** [fluxcd/terraform-provider-flux#604]
The `flux_bootstrap_git` resource should support the `commit_message_appendix` attribute - similar to the `--commit-message-appendix` flag the CLI does.

**Comment by swade1987** [comment]
@timofurrer this can already be configured in the git block inside the flux provider see [here](https://registry.terraform.io/providers/fluxcd/flux/latest/docs#commit_message_appendix)
