### ISSUE TITLE
A need for flexible Source and Kustomization resources. 

### ISSUE THREAD

**Issue by XtremeAI** [fluxcd/terraform-provider-flux#68]
Hi guys,

I've got a use case where I need to instantiate 1 git source and 3 kustomization resources with different paths (on the same source) to allow separation of workloads based on the environment I deploy to. 

Currently I struggle to use 'flux_sync' data provider as it generates both source and kustomization resources.

Is there a way to separately generate manifests for sources and kustomizations using this data provider? If not, would you consider adding such functionality to support beyond a basic usecase?  

My workaround ATM (which would be nice to avoid) is to manually prestage these 4 manifests with flux create --export and inject them into Terraform project. 

Regards, Alex

**Comment by phillebaba** [comment]
Yeah so this is a tricky one which currently does not have a good solution. Creating custom Kubernetes resources with Terraform is currently a pain as we know. Updating the data source can easily turn into a slippery slope to provide for everyones use case. But I am all ears if you have a suggestion in what you would like to change in the data source.

Another option that you could do which, well is not really nice, is to create a local helm chart in the same repo as your terraform HCL. That would allow you a temporary solution to deploy custom resources with terraform.

**Comment by XtremeAI** [comment]
The solution that would work perfectly for me and probably other folks as well is to just split the 'flux_sync' data provider into two data sources : the 'flux_gitrepo' and 'flux_kustomization' with all configurable params.

As it also falls into the topic. I also miss an option to install the 'extra components' with the default 'flux_install' data source. I expect to see them as a part of the data source 'flux_install' with optional key 'extra_components' set to a list of required extra  components.

Many thanks. I look forward to a solution in this space...

**Comment by phillebaba** [comment]
I do not think that this is a viable option at the moment as it would introduce a lot of complexity to the provider. Right now the goal is to mirror the functionality which the bootstrap command offers. Patching can be done by modifying the kustomization and patching changes.
