### ISSUE TITLE
[Bug]: Terraform plan want to replace whole kustomization.yaml and gotk-components.yaml

### ISSUE THREAD

**Issue by seraphblade2010** [fluxcd/terraform-provider-flux#697]
### Describe the bug

When I deploy fluxcd via terraform with the following code:
```
resource "flux_bootstrap_git" "flux_gitea" {
  depends_on = [gitea_repository.homelab]

  embedded_manifests = true
  path               = "cluster-k3s/bootstrap-flux"
}
```

on the first deployment everything works fine.
When I then execute terraform plan on the next day, it wants to change both files mentioned above.

I provided the plan ( approx. 25k lines ) below.

### Steps to reproduce

1. deploy fluxcd via terraform (see above for code)
2. let it sit for day
3. execute terraform plan without changes on the next day

### Expected behavior

No changes in deployment because I did not change anything.

### Screenshots and recordings

[tfplan.txt](https://github.com/user-attachments/files/15743513/tfplan.txt)

### Terraform and provider versions

Terraform v1.8.4 + Provider fluxcd/flux v1.3.0

### Terraform provider configurations

provider "flux" {
  kubernetes = {
    config_path = "~/.kube/config"
  }
  git = {
    url = "${var.gitea_url}/example/homelab"
    http = {
      username = "example"
      password = var.gitea_token
    }
  }
}

### flux_bootstrap_git resource

resource "flux_bootstrap_git" "flux_gitea" {
  depends_on = [gitea_repository.homelab]

  embedded_manifests = true
  path               = "cluster-k3s/bootstrap-flux"
}

### Flux version

v.2.30 (not explicitly defined, as seen in provided code snippet)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Would you like to implement a fix?

No

**Comment by swade1987** [comment]
@seraphblade2010 this is extremely weird and your terraform output looks like it's replacing everything line by line. Leave this one with me and I will take a look early next week when I am back to my desk. Does the same thing happen every time you execute "terraform plan"?

**Comment by seraphblade2010** [comment]
@swade1987 When I apply this weird change, it changes all files mentioned and keeps quiet for about a day, maybe two max.
But it happens every time when I start a terraform plan for the first time per day.

Additional Infos:
fluxcd is deployed on a 3-Node k3s cluster with a single master.
All three nodes are installed on a fully up-to-date Ubuntu 22.04 Image which was deployed with terraform in a proxmox cluster.

**Comment by swade1987** [comment]
@seraphblade2010 ive been unable to validate this but will try again this weekend and see if I can replicate it on a different type of cluster. Will report back in due course.

**Comment by seraphblade2010** [comment]
@swade1987 The problem just ... vanished?
Pretty dumbfounded why it just disappeared because I did not upgrade Terraform or fluxcd.
I guess this can be closed then ^^
