### ISSUE TITLE
Acceptance Tests

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/terraform-provider-flux#7]
Every resource should have acceptance test verifying their functionality. The acceptance tests should be built according to the methods described in the Terraform docs. After the tests have been built, an action should be added to always run the acceptance tests on each PR.

https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html

**Comment by relu** [comment]
I can help with this if you guys need a hand.

**Comment by phillebaba** [comment]
@relu I have added some basic tests to get started but I would appreciate any help expanding on these tests.

**Comment by relu** [comment]
Great, will get back soon with a PR to expand/improve on those a bit.
