### ISSUE TITLE
Helm Install support for bitbucket Cloud

### ISSUE THREAD

**Issue by absnmohammedsedex** [fluxcd/terraform-provider-flux#700]
### Description

Hi, 

We don't see any helm install support for bitbucket, there is only a github install of Flux2 via Terraform and helm. 
Do we have any other way to automate this besides running the bootstrap command? Thank you 

### References

https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/helm-install

### Would you like to implement a fix?

None

**Comment by swade1987** [comment]
@absnmohammedsedex unfortunately [this](https://github.com/fluxcd/terraform-provider-flux/issues/417#issuecomment-2044718449) comment covers the issue with Bitbucket
