### ISSUE TITLE
[Enhancement]: Example how to bootstrap Flux from existing repo outside Terraform

### ISSUE THREAD

**Issue by everythings-gonna-be-alright** [fluxcd/terraform-provider-flux#705]
### Description

All examples in this provider demonstrate how to bootstrap FluxCD when you create a repo in Terraform as a resource ( except helm). However, in reality, repo is not always declared in Terraform.
Moreover, in some cases, users can use one mono repo for many clusters. In this case, it is not really convenient to import the same repo into many terraform modules.
Can this provider allow FluxCD to bootstrap from Git using the HTTPS repo URL, username, and password?

**Comment by swade1987** [comment]
@everythings-gonna-be-alright please see the https documentation [here](https://registry.terraform.io/providers/fluxcd/flux/latest/docs#nestedatt--git--http)

**Comment by everythings-gonna-be-alright** [comment]
@swade1987 Oh. I didn't notice provider parameters. Instead, I tried to find them in the `flux_bootstrap_git ` resource. Framing effect.
Many thanks 🙏🏻

**Comment by swade1987** [comment]
> @swade1987 Oh. I didn't notice provider parameters. Instead, I tried to find them in the `flux_bootstrap_git ` resource. Framing effect.
> 
> Many thanks 🙏🏻

No problem at all @everythings-gonna-be-alright happy to help.
