### ISSUE TITLE
Access to KMS keys affected in v.0.7.1+ while bootstraping Flux via terraform

### ISSUE THREAD

**Issue by XtremeAI** [fluxcd/terraform-provider-flux#84]
Hi guys! 

The patch from yesterday has broken our project of flux deployment via Terraform and access to KMS keys in Flux due to a shift of requirement to have the annotation with AWS role on 'kustomize-controller' service account from the 'default' service account (https://github.com/fluxcd/flux2/blob/main/docs/guides/mozilla-sops.md) 

Before I could annotate the 'default' SA with Terraform before deploying Flux with your TF provider and Flux would be able to use the role after installation. Now if I deploy Flux via your Terraform provider and annotate the 'kustomize-controller' service account with the AWS role after installation Flux is not able to use the role until I restart the 'kustomize-controller' manually.

Can something be done in this regards, either: 
- kustomize-controller to monitor changes to 'kustomize-controller' service account and reusing the changes automatically
- giving an opportunity to provide Flux a custom service account with the predefined annotation for the purpose of KMS key access
- adding the ability to specify the annotation for 'kustomize-controller' service account in the data "flux_install" TF resource.

Thanks in advance

**Comment by phillebaba** [comment]
This should be possible by pushing your own kustomize file to the git repo which patches the service account.
https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests

I dont have an example on hand right now but it should be straight forward to replace the kustomize returned by the datasource with your own version which also contains the patches required to add IAM permissions to the new service accounts.

**Comment by XtremeAI** [comment]
Thanks for the suggestion but I foresee a problem in my case:  the IAM role is dynamically created by Terraform and the annotation is only known at runtime. Therefore I would need to push the kustomize file with Terraform to Gitlab. Not only I don't want to do that (to give anything write access to the git repo) but also when I was looking at TF Gitlab provider I did not see a way to make TF to commit data to a Gitlab repo.

**Comment by phillebaba** [comment]
Sadly this is more of a Gitlab provider issue that Flux provider issue. There is a PR to add this feature but there has been little progress in the last month.
https://github.com/gitlabhq/terraform-provider-gitlab/pull/350

Either way you will probably need to allow Terraform to commit to your repo if you want to do this type of thing. I cant really see another alternative. Do you have some other suggestion? The provider is limited to the same options as the bootstrap command is.

**Comment by voron** [comment]
>This should be possible by pushing your own kustomize file to the git repo which patches the service account.

It's not the problem to patch service account via Terraform. But it happens after flux deploy( as service account is created during flux deploy ) and kustomize-controller doesn't get service account changes. Are you saying that flux itself is smart enough to do something like "I'm patching kustomize-controller service account resource, thus I'll restart kustomize-controller after successful patch" ?

**Comment by phillebaba** [comment]
So does EKS IRSA require a Pod to restart if the service account is updated with a label? In that case I can see how this may be an issue. The problem is that Terraform is very limited in what you can do when modifying YAML, do you see some other solution to this problem?

**Comment by XtremeAI** [comment]
Yes, the Kustomize-controller pod requires a restart when you patch Kustomize-controller SA with the role. Someone mentioned it somewhere here or else where. I've tried it and it worked but obviously Kustomize-controller should pick this up without a restart.

**Comment by phillebaba** [comment]
Kind of makes sense now that I think about it, as IRSA works by injecting environment variables onto the pod when the specific service account is attached.

**Comment by stefanprodan** [comment]
> I'm patching kustomize-controller service account resource, thus I'll restart kustomize-controller after successful patch?

Patch the service account and the deployment by adding an annotation to the pod spec, Kubernetes will restart kustomize-controller on its own.

**Comment by XtremeAI** [comment]
Oh, yep, this helps. Many thanks!

**Comment by willejs** [comment]
Was the suggestion to patch the resources from within flux2 with kustomize? I am not sure this makes sense. 

I use this provider to generate the yaml and apply it with the kubectl provider as per the readme. At this point, terraform manages the flux2 components including the service account. 
My state holds a resource like so `kubectl_manifest.apply["v1/serviceaccount/flux-system/kustomize-controller"]` 
I cant really use a kustomization patch on the service account as terraform will notice the diff and try to reconcile the changes when I run TF, causing issues.

I think the original suggestion:

> adding the ability to specify the annotation for 'kustomize-controller' service account in the data "flux_install" TF resource.

Is maybe the best option? Patch manifest gen to overlay an annotation and surface it in the data source?
Maybe I'm missing something here...

**Comment by XtremeAI** [comment]
Nope, the suggestion and solution was to patch the resources from within TF. 
At the end I had to completely drop the 'fluxcd' TF provider as it provides no flexibility to install what I was the way I want PLUS it just did not work with kubectl resource if I tried to use it in a TF module. 
My solution was to apply the Flux2 provided install.yaml and patch it with raw yaml resource in TF.
