### ISSUE TITLE
Add documentation for GitLab

### ISSUE THREAD

**Issue by vikas027** [fluxcd/terraform-provider-flux#88]
We already have documentation for [GitHub](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/github) integration, it would be great if some documentation can be added for GitLab too.

**Comment by phillebaba** [comment]
There is an issue #8 tracking this and there have been multiple requests for this. As mentioned in those there is a PR in the GitLab provider to add support for git files, gitlabhq/terraform-provider-gitlab/pull/350, but it is currently stalled. I cant really create a GitLab guide until that PR is merged, so if you are in need of getting things working I would suggest checking to see if you could help out getting the last pieces in place.

I have started looking at a generic git example that would also work with GitLab, but that will require some work as there currently is no good git terraform provider out there.
