### ISSUE TITLE
Add toleration support for Deployment resources

### ISSUE THREAD

**Issue by trillejs** [fluxcd/terraform-provider-flux#93]
Hi,

I am trying to deploy flux and I saw that it is possible to add custom annotations/labels/etc... with a kustomize patch after flux is deployed: https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests

However the source controller is not deploying because there is no way for me to add tolerations to the node taints I want to deploy it to.

Is there a way of doing this that I am missing?

**Comment by stefanprodan** [comment]
Tolerations are a good candidate for manifestgen, this issue should be in flux2 repo.

**Comment by trillejs** [comment]
I added a discussion regarding this on the flux2 repository:
https://github.com/fluxcd/flux2/discussions/895

**Comment by stefanprodan** [comment]
Thanks 👍

**Comment by trillejs** [comment]
In case someone ever needs to add tolerations, there is a horrible workaround where you insert the tolerations before the container string in the deployment definition:
```terraform
install = [for v in data.kubectl_file_documents.install.documents : {
    data : yamldecode(v)
    content : replace(v, "containers:", "${local.toleration_string}\n      containers:")
    }
  ]
```
