### ISSUE TITLE
fluxcd updated even if fluxcd terraform provider version stays the same

### ISSUE THREAD

**Issue by monotek** [fluxcd/terraform-provider-flux#99]
the fluxcd terraform providers behaviour is a bit unpredictable.

if i run the same terraform definition after a week for example, a lot of changes regarding docker image version and so are introduced sometimes, changing the deployment in the cluster even if nothing in the terraform files has changed.

imho this should not happen.

updates to the k8s resources should only happen, if the terraform provider was updated too.

**Comment by stefanprodan** [comment]
The terraform provided downloads the manifests from GitHub, so if you don’t set a flux version in tf, you’ll endup with the latest stable release.

**Comment by monotek** [comment]
Hmmm... Any chance you'll add a fixed version by default to the next flux provider releases?

Feels a bit like using latest as docker image tag at the moment 😁

**Comment by phillebaba** [comment]
The question is what should the version default to in this case? We would need to update the flux version when we update the provider in that case. I can add a note about setting the version but the provider should behave in the same way as the CLI, which today uses the latest version when run, if nothing else is specified.

**Comment by monotek** [comment]
So the CLI with version 0.7.0 would install flux version 0.8.0 too, if available?

**Comment by phillebaba** [comment]
Yes I would expect that to happen, as the Terraform provider and CLI uses the same code in its core. The default value for the version parameter in the provider is derived from here in fluxv2. Which has the value `latest`.
https://github.com/fluxcd/flux2/blob/a2887f5776f48797ae77820192ad6d0d60743e21/pkg/manifestgen/install/options.go#L43

Looking at the CLI code the same default value is used. It can be verified if you run `flux bootstrap --help` which will return.
```
 -v, --version string             toolkit version (default "latest")
```

**Comment by monotek** [comment]
Ok, i will add it manually.

Nevertheless I think it should be documented that the config is not idempotent.
